### ISSUE TITLE
move save functionality from -cron to main script

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#104]
ATM in https://github.com/dandi/dandisets/blob/draft/tools/backups2datalad-cron#L33 we ave

```bash
datalad save -m "CRON update" -d . 00*
```

`save` should be performed at the end of the `update-from-backup` **only** for the subdatasets which were processed (so account for `--exclude`d ones to not be saved

**Comment by jwodder** [comment]
@yarikoptic Do you want the script to save the datasets that were *processed* or just the ones that were *changed* for this run?  This could make a difference if the script crashes after updating one or more datasets and is then rerun with the same options.

**Comment by yarikoptic** [comment]
> @yarikoptic Do you want the script to save the datasets that were _processed_ or just the ones that were _changed_ for this run?

Let's do _processed_ for the reason you outlined (thanks!). Also could make a difference if somehow there were "parallel" runs of the backup utility.
