### ISSUE TITLE
When processing all dandisets (no excludes), add/adjust total size to this `dandisets` description

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#109]
ATM we have About's of all dandisets nicely providing summary stat (e.g. "101 files, 2.6 TB") for each dandiset.
It would be useful also for this repository to have it similar like "XX dandisets, YYY TB total. DataLad super-dataset of all dandisets from https://github.com/dandisets".  That would allow us to get a quick assessment if our datalad'ified version covers all the data which https://gui.dandiarchive.org/ claims to have ("148 dandisets, 212 TB total" ATM)
For that to work reliably, update should be triggered only if script operates across all dandisets, and none is `--exclude`ed.

**Comment by jwodder** [comment]
@yarikoptic Note that the stats in the per-Dandiset "Abouts" are taken from the API rather than based on what's actually in the repositories, so this wouldn't necessarily give an always-accurate reflection of whether all data has been dataladified.  Do you still want to proceed?

**Comment by yarikoptic** [comment]
thanks! I did not realize it is coming from API.

Could we please change that to be based on the actual dataset file tree?

- could be done through manual traversal or might be better/easier to just use `datalad -f json_pp status --annex  basic` invocation and sum entries up  (we can't just use `git annex info` since we would miss non-annexed files)
- we should ignore `.dandi/*.json` and `.gitattributes` files

**Comment by jwodder** [comment]
@yarikoptic What about `dandiset.yaml` and `.datalad/*`?  Should those be ignored or counted?

**Comment by yarikoptic** [comment]
yeah, let's ignore those too - that should really make us match in size.
