### ISSUE TITLE
dandisets superdataset description says "1 Dandiset, 175.2 TB total. "

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#111]
Continuation to https://github.com/dandi/dandisets/pull/110 which resulted in https://github.com/dandi/dandisets/ to have "1 Dandiset, 175.2 TB total." probably corresponding just to https://github.com/dandisets/000108/tree/draft, not the summary of all dandisets.

FWIW invocation was as coded in https://github.com/dandi/dandisets/blob/draft/tools/backups2datalad-cron

**Comment by jwodder** [comment]
@yarikoptic Did you run the command with `--target` set to `/mnt/backups/dandi/dandisets` on drogon or something else?

**Comment by yarikoptic** [comment]
yes, I have ran on drogon what cron job runs 
```
flock -E 0 -e -n /home/dandi/.run/backup2datalad-cron.lock bash -c '/mnt/backup/dandi/dandisets/tools/backups2datalad-cron'
```
and that script does set --target from what I see to point to `/mnt/backups/dandi/dandisets`
