### ISSUE TITLE
Number of "Text Dandiset" on staging server grows

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#114]
https://gui-staging.dandiarchive.org/#/dandiset/search?search=Test%20Dandiset%20Wodder shows having 3 pages.

I guess they aren't cleaned up/removed properly at the end of the fixture?

**Comment by yarikoptic** [comment]
ok, transferred this issue to `dandisets` repo

**Comment by jwodder** [comment]
@yarikoptic I'm not sure about this.  Obviously, the cleanup works most of the time, or else there would be a lot more Dandisets.  What exactly do you want me to do about this?

**Comment by yarikoptic** [comment]
- investigate why/how we could be breeding more of those dandisets and ensure that we no longer do (well -- to the degree possible)
- wipe out those which are already populated on staging
