### ISSUE TITLE
dump logs at DEBUG level under `.git/dandi/backup2datalad/{timestamp}.log`

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#121]
Reflecting on difficulty to troubleshoot some tricky cases, https://github.com/dandi/dandisets/issues/113#issuecomment-1018817670, let's dump logs at DEBUG level into a file.

**Comment by jwodder** [comment]
@yarikoptic Is this supposed to be a per-Dandiset log file like the current log files, or a single file stored in the superdandiset?  Should DEBUG messages from third party libraries like urllib be included?

**Comment by yarikoptic** [comment]
Since everything is bolted on top of operation of superdataset, it is ok (if easier) to store one. We considered parallelization across dandisets (https://github.com/dandi/dandisets/issues/90) but I don't think we ever parallelized across dandisets, so dumping 1 log would suffice and would make it easier on "inodes" for us ;)  But if you see that it is easier to dump per dandiset (and in superdataset its own) - good enough for me too.

third party -- only if you want/see benefit from that, but might be too much I am afraid.
