### ISSUE TITLE
crash if any Zarr (.zarr/.ngff) asset is detected, do not even try to process that dandiset

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#126]
not even sure if that wouldn't happen "naturally" (i.e. some special API should be used), but if not -- as a stop gap measure we should stop trying to update a dandiset if it has one of those assets

**Comment by jwodder** [comment]
@yarikoptic At the moment, due to the fact that Zarr assets lack SHA256 digests, this will happen automatically, but any blob assets listed by the server before the Zarr will still be downloaded (though they won't be saved unless the Dandiset was published in-between).  Should a dedicated Zarr-ness check just be added next to the SHA256 check?

**Comment by yarikoptic** [comment]
cool, thanks! well, I guess I could figure out from the error message whenever it would say that some .zarr asset is lacking sha256 that it is one of those cases, but I would not mind also a more explicit error.

**Comment by jwodder** [comment]
@yarikoptic
* Note that the latest release of dandi-cli cannot tell whether an asset is a Zarr; the unreleased version on master is needed for that.  As such, I've added the check to #116.
* I was mistaken when I said that other assets downloaded in the Dandiset will not be saved; they will be saved, and the commit message will mention the number of assets yet to download.  Is this OK?
* Also note that this won't actually cause an error; it will just log a message, breeze through the remaining assets, and then continue on with the next Dandiset.

**Comment by yarikoptic** [comment]
Let's kick out release of dandi-cli asap - we already have too many changes unreleased... marked that late PR for release and merged.

> I was mistaken when I said that other assets downloaded in the Dandiset will not be saved; they will be saved, and the commit message will mention the number of assets yet to download. Is this OK?

wouldn't this cause difficulty to deduce later a possible state to branch off a release from? (because we would have some partial state saved)

I thought that I would prefer to error out as soon as we know that a given "state" cannot be instantiated for saving because it would need to contain a zarr so we do not forget about that.  But I guess we could proceed without a total kaboom for now if you think it would not cause some difficulty later on whenever we do add zarr subdatasets support

**Comment by jwodder** [comment]
@yarikoptic 

> wouldn't this cause difficulty to deduce later a possible state to branch off a release from?

I don't think so.  The assets are saved in creation order, and the commit uses the date of the last one for the author date, which is used to determine where to branch off of.

**Comment by jwodder** [comment]
Implemented in #116.
