### ISSUE TITLE
"Only some metadata updates" commits also contain changed (added?) assets

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#135]
looking at dandi@drogon:/mnt/backup/dandi/dandisets/000221 saw that none commit message says something about adding assets, and apparently commit message is indeed off, e.g.

```
commit d544e4412359e86dc36224a7540762b2b85e5f47
Author: DANDI User <info@dandiarchive.org>
Date:   Mon Mar 7 13:20:11 2022 +0000

    [backups2datalad] Only some metadata updates

 .dandi/assets.json                                             | 9468 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------------------------------
 sub-HI159/sub-HI159_ecephys+ogen.nwb                           |    2 +-
 sub-HI159/sub-HI159_ses-HI159-090418_ecephys+ogen.nwb          |    2 +-
...
```

ideally commit message should state what was done , e.g. 

X assets added, Y removed, Z changed, metadata changes

with a corresponding element missing if number is 0 or that change didn't happen.

**Comment by yarikoptic** [comment]
@jwodder Please review the effects of #136 if this issue could be closed

**Comment by jwodder** [comment]
There do not appear to have been any more "Only some metadata updates" commits with changed assets since #136 was merged.
