### ISSUE TITLE
cleanup test dandisets from staging + make sure that they do get deleted in case of fail/error

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#144]
There is a good number of test dandisets on staging: https://gui-staging.dandiarchive.org/dandiset/search?search=backups2datalad  . I thought we had this issue before and it was addressed to ensure that test dandisets are removed, but it seems that either it was fixed and those elderly dandisets were left behind, or may be issue still exist (I think we just weren't able to run tests in awhile in the https://github.com/dandi/dandisets/actions ).

**Comment by jwodder** [comment]
@yarikoptic The test code already ensures that test dandisets are removed, but https://github.com/dandi/dandi-archive/issues/965 was a problem for a while.

**Comment by jwodder** [comment]
Cleaned up.
