### ISSUE TITLE
add/update stats for dandizarrs

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#151]
repos under https://github.com/dandizarrs should gain description with # of files and total size similar (just without title for now) to those at https://github.com/dandisets

**Comment by yarikoptic** [comment]
I don't think #154 (merged awhile back) fixed that since all https://github.com/orgs/dandizarrs/repositories seems to still have "some default" for the description.

BTW -- related issue in DataLad land https://github.com/datalad/datalad/issues/6816 if you could address -- would be very welcomed!

**Comment by jwodder** [comment]
@yarikoptic The problem is that the repository descriptions aren't set until after the Dandiset is fully uploaded, which hasn't happened for 108 yet.

**Comment by yarikoptic** [comment]
ah, that explains it. Could we move that logic to operate at "per-zarr" level (seems to make more sense) and not wait for the entire "parent" dandiset?
