### ISSUE TITLE
Make zarr within dandiset github remote be called `github` not `origin

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#165]
For the zarr mentioned in https://github.com/dandi/dandisets/issues/160 I believe in that /mnt/backup/dandi/dandisets/000243/sub-S01/anat/sub-S01_T2w.ngff  I had to rename git remote from `origin` to `github`.  @jwodder , please make sure  that whenever we clone (?) `zarrarchive` from github as subdataset, it gets `github` rename, not `origin`, so we have it uniform with its superdataset naming

**Comment by jwodder** [comment]
@yarikoptic DataLad doesn't appear to have a way to set the remote name when cloning, so do I just manually rename the remote afterwards?

**Comment by yarikoptic** [comment]
eh. filed https://github.com/datalad/datalad/issues/6724 . Please indeed just use `git remote rename` for now after the clone.
