### ISSUE TITLE
populate-* -- use datalad's intefaces for get

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#172]
ATM running the `populate-zarrs` job floods the screen with outputs from git annex

```
get 0/0/0/14/14/98 (from web...) ok
get 0/0/0/14/14/71 (from web...) ok
get 0/0/0/14/14/84 (from web...)
get 0/0/0/14/14/87 (from web...)
get 0/0/0/14/14/97 (from web...)
get 0/0/0/14/14/88 (from web...)
get 0/0/0/14/14/96 (from web...)
```

and then `move`.  Should use datalad's interfaces (not sure if there is one for `move` though, filed https://github.com/datalad/datalad/issues/6736, let's start with `get`) to `get` so we have more concise progress reporting.

**Comment by jwodder** [comment]
@yarikoptic I'm assuming that the DataLad equivalent to `git-annex get` is [`datalad.api.get()`](http://docs.datalad.org/en/stable/generated/datalad.api.get.html), but that doesn't seem to have a way to specify `--from=web --not --in $backup_remote --and --not --in here`.  What is the proper function call to use here?

**Comment by yarikoptic** [comment]
yeah, indeed. So let's use "midlayer" -- those `AnnexRepo.call*` interface(s) I described in https://github.com/dandi/dandisets/issues/176#issue-1258403842 , e.g. `AnnexRepo.call_annex_records` to which you pass all command line options you like.
