### ISSUE TITLE
populate* -- parallelize "for p in dirs:" loops; update_from_backup -- "for d in self.get_dandisets("

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#173]
ATM there is `--jobs` which is passed over to git-annex.  I think, similar to `dandi-cli` we could have `-J dirs[:git-annex]` syntax and allow for parallel "processing" of those datasets with parallel uploads within each one. Similarly within `upate_from_backup`.

Note: not sure how much of benefit it would be for the `populate` since at the level of dandisets files are likely to be heavier so bottleneck would be bandwidth and thus parallelization across dandisets would not matter as much.  But for `populate-zarrs`, where it is mostly CPU bound in external tools (git-annex/rclone) from what I see due to loads of tiny files - I expect to see benefits. 

Also relates to "UX", e.g. #172 to make outputs sensible, although not sure if that would remain possible.  At least in the logs we should add the thread id to be logged by default to be able to "group" logs for the same thread together.

**Comment by jwodder** [comment]
@yarikoptic What should happen if an error occurs in one of the jobs?  Should everything stop immediately?  Should it continue with the jobs that are currently running but not start any more pending jobs?  Should everything else run to completion?

**Comment by yarikoptic** [comment]
I was just to file an issue about that -- ATM failed `annex move` in one zarr fails entire `populate-zarrs` which is ... suboptimal.  Filed https://github.com/dandi/dandisets/issues/176 specifically for retrying, and in respect to the question -- yes, we should process other zarrs and then error out if any of them errored out, i.e. to not fail as soon as any fails.  May be later, if I see the need, we would add an option to stop as soon as any item in the loop errors out.

**Comment by yarikoptic** [comment]
FWIW -- ideally with `-J 0` it should remain serial to ease debugging etc.  What about may be using an already existing helper I coded in datalad?  `ProducerConsumer`: https://github.com/datalad/datalad/blob/HEAD/datalad/support/parallel.py#L71 . It already has an option to instruct either to fail early and I believe goes serially for jobs=0. Also it allows for parallel "producing" .  Not sure if it would anyhow interfere with current async nature of code we have here.

**Comment by yarikoptic** [comment]
looking at ProducerConsumer and doc/code for `reraise_immediately` I don't think it would be entirely doing what you ask/I want above -- even if `reraise_immediately == False`, I think (and as [this test](https://github.com/datalad/datalad/blob/32f3e760fcce7856c515f28c48263dfd97c385fe/datalad/support/tests/test_parallel.py#L176) shows) it would only finish processing what was already submitted and not necessarily all other jobs. So it would be for consumer to "guard" with try/except and then just return a record on either it succeeded or not and external logic to decide to either error out if any consumer returned non-success.

**Comment by yarikoptic** [comment]
this should also help with reporting where (in which dandiset or zarr dataset) error happened, since now it seems to be impossible to determine exactly because nothing in traceback includes the path e.g. in https://github.com/dandi/dandisets/issues/191 .

**Comment by yarikoptic** [comment]
@jwodder please prioritize this issue.

**Comment by jwodder** [comment]
@yarikoptic 

* What should the default number of workers be?
* Currently, we limit the number of Zarrs processed at once to 32.  Should this limit continue to be used as a Zarrs-per-Dandiset limit or as a limit on the total number of Zarrs processed at once across all in-progress Dandisets?

> At least in the logs we should add the thread id to be logged by default to be able to "group" logs for the same thread together.

I'm going to implement this using asynchronous programming, which doesn't use threads, so there are no thread IDs.  I could give the workers ID numbers, but I don't see much point to that as long as the log messages always include the Dandiset ID.

Also, could you merge #202 soon?  It'll make the Git history easier to work with.

**Comment by yarikoptic** [comment]
- Could as well be 1 but could be 5 -- we should be able to provide in CLI as we already do with `-J`.
- if possible to make 32 shared limit across dandisets -- would be great!  If not - reduce to 6 or so?
- ok, let's see how it would look with dandiset IDs to be present in every log msg
- #202 is merged now, thanks!

**Comment by jwodder** [comment]
@yarikoptic Oh, sorry, I meant to ask for #196 to be merged.

**Comment by jwodder** [comment]
@yarikoptic In addition to the process-wide logfile saved in the superdataset in `.git/dandi/backups2datalad`, you may recall that there are also Dandiset-specific logfiles saved in each Dandiset dataset in `.git/dandi/logs` (though these logfiles are deleted if no changes were made to the repository).  Unfortunately, implementing parallel Dandiset backups will mess with the latter logs; we can either get rid of them (Do you even use them that often?) or limit them to just the log messages emitted by `backups2datalad` itself (excluding log messages from HTTP libraries and the like).  Which would you prefer?

**Comment by yarikoptic** [comment]
I do quite use them -- still debugging 000108, and the sizes of those logs probably is the major storage impact on drogon ATM ;)

I guess the "difficulty" is that if done via async, it would be in the same process and it is impossible to establish different logging targets per each worker since it is all in the same process?  May be then we could avoid `async` and just have it done implemented via multiprocessing children?

but , in principle, I guess if there is a guaranteed prefixing for each dandisets in the logs, I would be ok if it would all go in super dataset's `.git/dandi/logs/`, but would such prefixing be feasible from all the levels?

**Comment by jwodder** [comment]
@yarikoptic In the current draft, I believe the only Dandiset-specific log messages that aren't prefixed are the DEBUG messages emitted whenever a subcommand is run (because that would require passing around too much data constantly), but those include the directory in which the command is run, so you can still tell what they're operating on.

**Comment by yarikoptic** [comment]
I am ok with that compromise.
