### ISSUE TITLE
manages to miss some deletions

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#174]
per https://github.com/dandisets/000026/issues/4 report -- see the details there. Indeed even after the super-fresh run the file is still there:
```
[rawdata/sub-I38/ses-SPIM/micr/sub-I38_ses-SPIM_sample-BrocaAreaS02_stain-Calretinin_chunk-47_SPIM.ome.tif](https://github.com/dandisets/000026/blob/b3c46528117ea311e71c868e0fa2f1b88280df3e/rawdata/sub-I38/ses-SPIM/micr/sub-I38_ses-SPIM_sample-BrocaAreaS02_stain-Calretinin_chunk-47_SPIM.ome.tif)
```
so some logic is defective in detecting/handling deletions .  

FWIW: the .dandi/assets.json still contains it but there is no mentioning of that path in the logs for the past week or so.

**Comment by satra** [comment]
may also want to check if it's in assets.json on the s3 bucket, which could be another way of getting asset metadata without paginating through the api.

**Comment by yarikoptic** [comment]
wouldn't hurt to check, but for backup I would prefer to go by what API knows so we do not "chain" the possible sources of the bugs (that `assets.json` is also not given by gods, is it?) ;)

**Comment by satra** [comment]
> is also not given by gods, is it?)

if the api server is a god then yes.

**Comment by yarikoptic** [comment]
Well, in our design DB is the holy grail. API is the only one talking to it directly. It is as close to God we can get ;-)
