### ISSUE TITLE
Need an alternative way to set commit date

### ISSUE THREAD

**Issue by jwodder** [dandi/dandisets#182]
Backing up Zarrs in a Dandiset happens concurrently, including the commit at the end.  Currently, the commit date is set using [`custom_commit_date()`](https://github.com/dandi/dandisets/blob/4d5ffe1e758cf3a42f80287049363cb614f3a3ee/tools/backups2datalad/util.py#L268), which simply sets environment variables, which are process-wide.  This has the potential to result in a Zarr commit having the wrong timestamp if it is committed at the same time as another Zarr and `GIT_AUTHOR_DATE` is read in an unfavorable order.

Unfortunately, `datalad.api.save()` does not have a way to set the commit date.  The next best option would be to invoke `git commit` directly, passing a modified environment dict to the subprocess, which would require the backup script to ensure itself that everything that needs to be committed is `git add`ed.

**Comment by yarikoptic** [comment]
Could we just have a threading lock context manager around `api.save` where within locked state we set `custom_commit_date()`? that would prevent two concurrent saves to be executed

**Comment by jwodder** [comment]
@yarikoptic I'm worried about what that would do to the runtime, as saves can take several minutes on large Zarrs.

**Comment by yarikoptic** [comment]
indeed `save` takes awhile on heavy hierarchies, but I would not expect many zarrs needing saving (meaning that they were updated) at the same time. So I would do this quick & easy fix until we spot that it became a bottleneck and then see what we should do about that (there is fake dates hook ups already, so might be a matter to "interface" to those points but not sure if worth the pain ATM)
