### ISSUE TITLE
provide/adjust dandiset stats/description/url for a dandiset upon push

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#20]
ATM those on https://github.com/dandisets/  have no metadata on them. Hard to impossible to find anything unless know which one you are looking for. Ideally within https://github.com/dandi/dandisets/blob/master/tools/backups2datalad.py we should
- upon initial publish for each repo provide URL which would point to `https://identifiers.org/DANDI:<ID>` e.g. https://identifiers.org/DANDI:000006 .
- upon every push update description so it becomes
  `<files unicode> #files <storage unicode> size,  Contact, Description` to mirror what we have on https://gui.dandiarchive.org/#/dandiset .

- there should be a way to "force trigger" update of descriptions/url (e.g. to populate currently already pushed to github datasets or later if we change what we display there etc)

**Comment by jwodder** [comment]
@yarikoptic The "file" and "storage" symbols on gui.dandiarchive.org appear to be part of a custom font rather than actual Unicode characters.  There are some Unicode characters similar to the "file" glyph, but they don't show up on my computer.  I can't find a Unicode character resembling the "storage" glyph.

**Comment by jwodder** [comment]
@yarikoptic What exactly should the semantics of the "force trigger" option be?  Should it cause the script to run as normal but also set the description & URL for every repository, regardless of whether they're being pushed to, or should it cause the script to only set the description & URL for repositories, not even bothering with syncing?

What if the script always set the description & URL for every repository operated on regardless of whether they're pushed to?

**Comment by yarikoptic** [comment]
storage: ⛃ (well -- for https://en.wikipedia.org/wiki/Draughts but looks close enough), file -- I failed to find one. Which one you found?  Oh well -- could be `X files, Y GBs` without fancy unicode.

> ... set the description & URL for repositories, not even bothering with syncing?

I think it would be useful to support such a dedicated command 

> What if the script always set the description & URL for every repository operated on regardless of whether they're pushed to?

would be wasteful/take time as number of dandisets grows.  Those could change only whenever a dandiset is updated (we would be pushing) or we decide to change something (formatting etc), which would be triggered manually via a dedicated command
