### ISSUE TITLE
move partial-zarrs to some speedier disk partition

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#222]
drogon was designed as a backup server, and its main /mnt/backup/dandi/ is on spindles and not optimized for high throughput. That seems to lead to IO bottleneck on the server ATM.  I think we can lighten its load up if we move operation on partial-zarrs (before they are established) to operate while on some speedy SSDs.  I think we still have empty bays in that server. I will see how much space we use now for them, and will see into adding

@jwodder what would be the most "graceful" migration strategy for us, e.g. is operation on partial-zarrs "restartable" or we would need to just do them from scratch?  is there an easy way to somehow tell current job to just not add more of new ones so it could gracefully finish what it had been doing already?

**Comment by jwodder** [comment]
@yarikoptic 

> what would be the most "graceful" migration strategy for us, e.g. is operation on partial-zarrs "restartable" or we would need to just do them from scratch?

We would simply need to move the directories while the script isn't running (and also update the path in the shell script).

> is there an easy way to somehow tell current job to just not add more of new ones so it could gracefully finish what it had been doing already?

No, the only option is to kill the script.

**Comment by yarikoptic** [comment]
> No, the only option is to kill the script.

would we need to remove/let it recreate those partial-zarrs which it didn't finish yet?  I see a good number of them which are there since June:

```
(base) dandi@drogon:/proc/1006503/cwd/.git$ ls -l /mnt/backup/dandi/partial-zarrs/
total 0
drwxr-sr-x 1 dandi dandi  64 Jun 16 07:29 0552de37-1362-4b4a-91ea-f289f7f16bba
drwxr-sr-x 1 dandi dandi  64 Jun 16 06:36 0aa19d5e-09b1-48d4-a5a9-ddce11f8f48c
drwxr-sr-x 1 dandi dandi 114 Jul 13 11:27 0b0e4715-877c-4e7f-af77-8555ca605c2d
drwxr-sr-x 1 dandi dandi  64 Jun 16 06:52 1a81fe53-631f-4680-9483-002dbd7e390e
drwxr-sr-x 1 dandi dandi  64 Jun 13 22:45 401750d3-75af-4b1a-9771-82cd5edec743
drwxr-sr-x 1 dandi dandi  64 Jun 13 22:45 4a87b852-1dfe-4886-b6dd-6342365553ea
drwxr-sr-x 1 dandi dandi 126 Jul 13 11:45 5df9d6d5-617d-401b-a101-6c8d36e03540
drwxr-sr-x 1 dandi dandi  64 Jun 16 03:56 5f764317-2c0c-4158-b74c-e21713fca85a
drwxr-sr-x 1 dandi dandi  64 Jun 16 07:29 73083a39-0ecc-4d83-8c30-bf97b519a49e
drwxr-sr-x 1 dandi dandi 126 Jul 13 11:53 7a9935c9-87e7-4ddf-b9d8-9da00c46202b
drwxr-sr-x 1 dandi dandi  64 Jun 29 14:28 896afc7c-b419-46c5-ac31-d915426c34fc
drwxr-sr-x 1 dandi dandi  64 Jun 16 07:24 8d2231b3-8209-4dea-bc82-a59c9a1fff8a
drwxr-sr-x 1 dandi dandi  64 Jun 13 22:46 9c359b3e-21a6-464c-a180-c8c114d8c01a
drwxr-sr-x 1 dandi dandi  64 Jul 10 16:11 a5bf9ff9-d081-4605-a6e1-ec8554ae4155
drwxr-sr-x 1 dandi dandi  64 Jun 16 03:52 b1769e87-423c-4b9f-82f3-b032f7363db8
drwxr-sr-x 1 dandi dandi 114 Jul 13 10:07 c870fffc-0631-403c-884c-8e72e0ea0ff6
drwxr-sr-x 1 dandi dandi  64 Jun 29 16:11 cff19d03-ed92-4ec0-bca1-2237cae5c9f0
drwxr-sr-x 1 dandi dandi  64 Jul 10 19:25 d28263d3-e02b-489f-8637-86b0067052ce
drwxr-sr-x 1 dandi dandi  64 Jun 13 22:46 dac9b7da-b880-47a2-aa55-53888db8443a
drwxr-sr-x 1 dandi dandi 114 Jul 13 10:35 e2ac17c5-417f-4927-be39-289aae256fc7
drwxr-sr-x 1 dandi dandi  64 Jun 13 22:46 e4d76c7e-76f9-434a-9d5d-50003d4244f4
drwxr-sr-x 1 dandi dandi 114 Jul 13 11:48 ef1987d4-a020-459d-b502-458b94388499
drwxr-sr-x 1 dandi dandi 114 Jul 13 11:01 ffe18d8f-799a-4f92-aae1-700c34d53a66
```
so I guess take awhile to populate?

**Comment by jwodder** [comment]
@yarikoptic

> would we need to remove/let it recreate those partial-zarrs which it didn't finish yet?

I don't think removing them should be necessary.

**Comment by yarikoptic** [comment]
I have created BTRFS partition striped across two SSDs (thus no data redundancy, it better doesn't fail) at `/mnt/fast/` and there is `/mnt/fast/dandi` folder.  Please move partial-zarrs "work" over there (I guess folder could be symlinked at old location so no adjustment to configuration would be needed). Partition is not too big (37G) but I think it should be enough for partial zarrs generation.  If we do run short of space I will get dedicated SSD drives for this purpose.
I hope this would make the whole process a little more performant.

**Comment by jwodder** [comment]
Moved partial-zarrs to `/mnt/fast/dandi`.

**Comment by jwodder** [comment]
@yarikoptic Now that partial-zarrs and dandizarrs are on different filesystems, moving a completed Zarr from the first folder to the second (using `pathlib.Path.rename()`) fails with:

```
OSError: [Errno 18] Invalid cross-device link: '/mnt/fast/dandi/partial-zarrs/d2409416-5473-44a9-905b-356c511c1c92' -> '/mnt/backup/dandi/dandizarrs/d2409416-5473-44a9-905b-356c511c1c92'
```

What's the preferred way to move a git-annex repo across filesystems?

I've stopped the Zarr backup for now.

EDIT: I'm thinking that just using [`shutil.move()`](https://docs.python.org/3/library/shutil.html#shutil.move) should work.  Should I go with that?

**Comment by yarikoptic** [comment]
sure  - use whatever `move` you would like which would achieve the goal. Just make sure that all symlinks/permissions are moved correctly.  Also, if you could then adjust git annex description after the move via `git annex init "$HOST:$NEWLOCATION` or alike -- would be great, so description doesn't stay pointing to partial-zarrs.

**Comment by yarikoptic** [comment]
I believe this was done already, so closing. @jwodder please reopen if anything else to be done on this regard.

FWIW, drogon feels much better and dm-0 is not bottlenecking now
