### ISSUE TITLE
use annex registerurl with  -c annex.alwayscompact=false

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#228]
in particular of great importance for zarr "files" and at large might resolve https://github.com/dandi/dandisets/issues/225 .

We will need future (ATM) release of git-annex.

ref: https://git-annex.branchable.com/todo/registerurl__58___do_changes_in_journal___34__in_place__34____63__/#comment-cb068404f17c44b9f90ea78a70d102cd

**Comment by yarikoptic** [comment]
ok, let's do it since timings showed notable improvement for some use cases - see https://github.com/dandi/dandisets/issues/225#issuecomment-1212196097

- check if `datalad.support.external_versions.external_version['cmd:annex'] >= '10.20220724'` and error otherwise
- add `-c annex.alwayscompact=false` to the `registerurl` invocation

**Comment by jwodder** [comment]
@yarikoptic Should this also be added to `addurl`?

**Comment by yarikoptic** [comment]
Good catch, I would assume it would indeed benefit too. Please do that too
