### ISSUE TITLE
Idea: dandiset Version "wide" state sha256s

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#239]
NB filing it in dandisets but eventually might be moved or formalized within dandi-archive.

ATM out backup script fetches the entire list of assets from the server to typically just verify that there is no changes to fetch. It is relatively expensive operation especially on such heavy dandisets as 000026.

dandi-archive DB model does not have git-like "state" descriptor which could provide similar to git statement that "there is no changes", but I think we could easily and cheaply introduce it by formalizing "checksum"ing procedure at different levels and simply base it on `last-modified` time stamp

- blob - "checksum"(last-modifed) on blob record
- asset - "checksum"(last-modified) on asset record (IIRC includes metadata etc)
- {dandiset_version}/assets - "checksum"(checksum("asset") for "asset" in assets)
- dandiset only - "checksum"(last-modified) 
- dandiset full - "checksum"([dandiset only, {dandiset_version}/assets])

I think all of those could be VERY QUICKLY done at DB level on dandi-archive, and it would allow us to avoid bombarding API server.

WDYT @jwodder ?

**Comment by jwodder** [comment]
@yarikoptic So the API would expose some number of endpoints for getting these checksums (or just the last one?), the datasets would store the current value of each checksum when making or updating a backup, and the script would check whether a backup is needed by comparing the stored checksums to the checksums on the server?  Sounds good.

**Comment by yarikoptic** [comment]
> So the API would expose some number of endpoints for getting these checksums (or just the last one?)

for us to decide I guess, and insofar I see the last one of the most value ATM. 
Although if we could get a list of assets even without metadata but only with those checksums -- we would have enough for making decision on either to update or not. But so far I do not see big penalty from requesting full metadata records if we are to request the full list of assets, so not sure if that particular step would be of notable benefit.

I guess we might also benefit from the `{dandiset_version}/assets ` being exposed since that would allow to not bother fethcing the list of assets.  Since getting metadata on dandiset itself is quick, we would already benefit from having this single one instead of the last one (just would need 2 API calls instead of 1).

> ...  the checksums on the server?

correct. Glad you like it.  We might need to formalize it as a spec/recommendation for being developed against dandi-archive/

**Comment by yarikoptic** [comment]
@satra suggested a possible quick "temporary" workaround -- to use the ETag of the manifest dump on S3 for the draft version. URL to that location could be retrieved from dandiset metadata record.  Pros: available now. Cons: relies on a "derivative" detached from the DB, dumping of which could also get broken  so we would end up with outdated state of dandisets.

**Comment by jwodder** [comment]
@yarikoptic @satra 

> URL to that location could be retrieved from dandiset metadata record

Where in the Dandiset metadata?  If I look at [the metadata for 000029](https://github.com/dandisets/000029/blob/6a65b28f5d8749c3ce79994ef5968f7cafc3bc52/dandiset.yaml), the most likely candidate seems to be the URL under the "`manifestLocation`" key, but that's just the API's asset listing for the Dandiset.

**Comment by satra** [comment]
ah yes, for draft assets i think we just return the API endpoint. if you look at a versioned dandiset, you'll see what the s3 path looks like for a manifest. there exists a similar path for a draft dandiset to, the api doesn't expose it at this point, but could.

**Comment by yarikoptic** [comment]
indeed not in metadata. URL could be grammatically created I guess, although that would be suboptimal:

```
(base) dandi@drogon:/mnt/backup/dandi/dandisets/000026$ s3cmd ls  -c ~/.s3cfg-dandi-backup  s3://dandiarchive/dandisets/000026/draft/assets.yaml
2022-07-22 07:14     53544670  s3://dandiarchive/dandisets/000026/draft/assets.yaml
```

**Comment by jjnesbitt** [comment]
Currently a draft version's `modified` field is updated every time an asset within that draft version is created, updated or destroyed. If we can assume this, why couldn't a simple reading of last modified for that dandiset's draft version suffice?

**Comment by jjnesbitt** [comment]
Also, currently the dandisets listing endpoint embeds each dandiset's draft version into the response, so this last modified time could be viewed in bulk through the dandiset list endpoint.

**Comment by yarikoptic** [comment]
To say the truth I was not aware that " a draft version's modified field is updated every time an asset within that draft version is created, updated or destroyed. " . Overall, I think, it could provide us a quick/easy way to check for changes.  I guess we could make it "optional" (or forced to ignore) so we could once in a while (e.g. once a week) run a "full sweep" and alert us (error out at first) whenever dandiset assets did get some changes but that modification time was not updated. WDYT @jwodder - sounds feasible ?

**Comment by jwodder** [comment]
@yarikoptic Would we compare the server's timestamp against the author date of the local dataset's HEAD commit (which is based on the Dandiset "modified" timestamp at the time of the last backup), or would we store the timestamp in some file in the dataset?

> alert us (error out at first)

Erroring out might require too many changes to the code.  It'd be easier if we just periodically did a backup that ignored the server's timestamp (the same as the current behavior).

**Comment by yarikoptic** [comment]
I would probably just store in a file (e.g. `.dandi/assets-state.json` with "timestamp" or alike, happen we want to use/extend later) since relying on commit makes it difficult to be able to tune/fix that dandiset.  

> It'd be easier if we just periodically did a backup that ignored the server's timestamp (the same as the current behavior).

ok, let's just log at WARNING or ERROR level, and indeed have an option to trigger current behavior once a week or so

**Comment by jwodder** [comment]
It appears that the "modified" property of Dandisets is not updated when an asset is uploaded to the Dandiset, as this script demonstrates:

```python
import os
from pathlib import Path
from tempfile import TemporaryDirectory
from time import sleep

from dandi.dandiapi import DandiAPIClient
from dandi.files import dandi_file

with DandiAPIClient.for_dandi_instance(
    "dandi-staging", token=os.environ["DANDI_API_KEY"]
) as client:

    d = client.create_dandiset(
        "Test Dandiset",
        {
            "schemaKey": "Dandiset",
            "name": "Test Dandiset",
            "description": "A test Dandiset",
            "contributor": [
                {
                    "schemaKey": "Person",
                    "name": "Wodder, John",
                    "roleName": ["dcite:Author", "dcite:ContactPerson"],
                }
            ],
            "license": ["spdx:CC0-1.0"],
        },
    )

    dandiset_id = d.identifier
    print("DANDISET ID:", dandiset_id)
    print("DANDISET MODIFIED:", d.modified)
    try:
        with TemporaryDirectory() as tmpdir:
            dspath = Path(tmpdir)
            p = dspath / "file.txt"
            p.write_text("This is test text.\n")
            df = dandi_file(p, dandiset_path=dspath)
            sleep(3)
            print("Uploading file.txt ...")
            df.upload(d, {"description": "A file"})
            d = client.get_dandiset(dandiset_id, "draft", lazy=False)
            print("DANDISET MODIFIED:", d.modified)
            sleep(3)
            d = client.get_dandiset(dandiset_id, "draft", lazy=False)
            print("DANDISET MODIFIED:", d.modified)
    finally:
        print("Deleting Dandiset ...")
        d.delete()
```

Output from one run:

```
DANDISET ID: 203080
DANDISET MODIFIED: 2022-08-03 13:41:29.426375+00:00
Uploading file.txt ...
DANDISET MODIFIED: 2022-08-03 13:41:29.426375+00:00
DANDISET MODIFIED: 2022-08-03 13:41:29.426375+00:00
Deleting Dandiset ...
```

**Comment by satra** [comment]
the default listing in dandiarchive is by modification time, so somewhere it is happening, but perhaps delayed.

i think it's still a bug if asset addition doesn't modify the dandiset.  technically it should update on add or modification (such as outcome of checksumming/validation, which are out of band processes). 

also `dateModified` is not being set on dandiset metadata. filed: https://github.com/dandi/dandi-archive/issues/1227

**Comment by jjnesbitt** [comment]
@jwodder is your script retrieving a version or a dandiset itself? The pertinent version is updated on asset modification, but the dandiset containing that version is not. Regarding synchronous behavior, the version modified field is updated in the request thread, so there's no delay to it.

**Comment by jwodder** [comment]
@AlmightyYakob It's retrieving a Dandiset.  I can confirm that the "modified" property of the version is updated.

**Comment by jwodder** [comment]
@yarikoptic When backing up a Dandiset, if a save happens partway through due to there being a published version that some assets were added after, should the `assets-state.json` file be updated at this partial save point, and, if so, what timestamp should it contain?

**Comment by yarikoptic** [comment]
Do we know time stamp of published version?  I would expect it to be **before** the time stamp of the updated draft **but** I am afraid there is no guarantee.  
May be then let's not bother saving that intermediate state within "draft" branch for which we do not unambiguous metadata and just produce that commit in the "release" branch for that published version? 

Is this question "directly" related to this issue or you discovered a possible "generic" logic flaw while working on it @jwodder ?

**Comment by jwodder** [comment]
@yarikoptic

> Do we know time stamp of published version?

Yes.

> May be then let's not bother saving that intermediate state within "draft" branch for which we do not unambiguous metadata and just produce that commit in the "release" branch for that published version?

There's currently a nontrivial portion of the code dedicated to saving the asset state at/around the point at which versions were published so that the commits on the release branch are close to minimal.

> Is this question "directly" related to this issue or you discovered a possible "generic" logic flaw while working on it

It's mostly a question of where exactly in the update procedure to put the "Update `assets-state.json`" logic.

**Comment by yarikoptic** [comment]
> > May be then let's not bother saving that intermediate state within "draft" branch for which we do not unambiguous metadata and just produce that commit in the "release" branch for that published version?
> 
> There's currently a nontrivial portion of the code dedicated to saving the asset state at/around the point at which versions were published so that the commits on the release branch are close to minimal.

yes, and that is good.  But there would be cases where we cannot deduce reliably, wouldn't they?
 How did we decide on that time stamp before -- wasn't it the latest modification time for any of the affected assets but checking that it is after prior commit timestamp and not after the overall published/draft version (i.e. if violated -- the case where we cannot deduce timestamp to use, just avoid that intermediate state)?  

> It's mostly a question of where exactly in the update procedure to put the "Update `assets-state.json`" logic.

at the moment of saving/committing that state of assets.  (and related: I guess the `gc` we added recently in #243 should be ran only for the "final" commit since we cannot reliably know that those assets were removed in some of the intermediate states)

**Comment by jwodder** [comment]
@yarikoptic 

> How did we decide on that time stamp before -- wasn't it the latest modification time for any of the affected assets but checking that it is after prior commit timestamp and not after the overall published/draft version (i.e. if violated -- the case where we cannot deduce timestamp to use, just avoid that intermediate state)?

When taking a backup of a draft Dandiset, all of the version information for the Dandiset is fetched and sorted by the `created` timestamps before fetching any assets.  While listing assets from the server (retrieving them in "created" order), if the current asset has a `created` timestamp later than or equal to the `created` timestamp of the next version, we pause, save what we currently have (using the highest `created` timestamp of the assets seen for the current version as the commit author date), and then resuming processing assets.

> at the moment of saving/committing that state of assets

I'm unclear what your answer to [my original question](https://github.com/dandi/dandisets/issues/239#issuecomment-1204051811) is.

**Comment by yarikoptic** [comment]
the answers are:
- `assets-state.json` should be updated at every save point, including the "partial save point"
- if it is "partial save point" - save using  "created timestamp of current asset"

**Comment by jwodder** [comment]
@yarikoptic 

> we could once in a while (e.g. once a week) run a "full sweep" and alert us (error out at first) whenever dandiset assets did get some changes but that modification time was not updated.

When doing such a sweep, if any assets are "garbage collected" (see #231, #243), should that trigger an error or not?

**Comment by yarikoptic** [comment]
Could it be an option we would enable (e.g. `--gc-assets=not,do,error` or alike) so e.g. for that full sweep we could set it explicitly to `--gc-assets=error`, and keep availability of `do` for conscious handling of "error" cases, and by default have it `not`, i.e. not bother and not do even a check?

**Comment by jwodder** [comment]
@yarikoptic That would be possible, but I'm not clear on why you want such configurability.  For one thing, I don't believe the asset GC check has any notable effect on efficiency, so I don't see why you'd want to leave it off by default, and if we limit the options to just `do` and `error`, I'm not sure why you'd want a value other than `error` when doing a full sweep.

**Comment by yarikoptic** [comment]
agree -- just `do` and `error` with `error` being the default but so we could `do` it after analysis of an `error`.
