### ISSUE TITLE
More efficient dirt check needed

### ISSUE THREAD

**Issue by jwodder** [dandi/dandisets#256]
The backup of 000108 is currently stalled at the very first step, checking whether the dataset is dirty, which it does by evaluating [`ds.repo.dirty`](https://github.com/datalad/datalad/blob/85102f65ce3f7024c6d0de85a9839cff4171b2fb/datalad/support/gitrepo.py#L2239-L2260), which in turn calls `git status`, collects the entire output, and then (in order to handle some sort of edge case) does another status check of some sort, which seems to involve creating a list of every file (with additional data) in the dataset and its subdatasets.

At the moment, the script has been evaluating this one property for almost seven hours, and though the memory usage started out at 0.2%, it's now up to 64.2%.  Clearly, a more efficient approach is needed.  The best idea I have is just running `git diff --quiet HEAD`, but that ignores untracked files.

@yarikoptic Thoughts?

**Comment by yarikoptic** [comment]
No immediate ideas really besides introducing some special case for 000108 to avoid testing for untracked files. Could be done with datalad's `status(untracked='no')` and may be also adding for submodules to test only `eval_subdataset_state='commit'`

**Comment by yarikoptic** [comment]
- didn't check at which stage it happens, but I think that dirty checking should be delayed all the way until we are actually proceeding with an update. Is that the case?
- overall strategy would be to not carry installed zarr submodules in dandisets:
   -  upon completion of update, uninstall all zarr submodules (we do have them locally among `dandizars/` folder). That would guarantee that we do not carry some dirty state of a zarr in its clone within corresponding dandiset. Absence of pre-install submodules would make dirty check fast!
     - if any zarr needs to be updated, it would be installed/updated to the desired state (thus clean since installation should be clean) and at the end of the update uninstalled.

**Comment by jwodder** [comment]
@yarikoptic 

> didn't check at which stage it happens, but I think that dirty checking should be delayed all the way until we are actually proceeding with an update. Is that the case?

The dirt check already happens after checking the assets stat timestamp.  What exactly do you mean by "until we are actually proceeding with an update"?

> overall strategy would be to not carry installed zarr submodules in dandisets:

Why even both installing the Zarrs in the Dandiset datasets in the first place?  We could just register them as gitmodules but not check them out there — though I'm not sure how best to do that with DataLad.

**Comment by yarikoptic** [comment]
> The dirt check already happens after checking the assets stat timestamp. What exactly do you mean by "until we are actually proceeding with an update"?

likely just what you said - until we do early check for timestamp

> > overall strategy would be to not carry installed zarr submodules in dandisets:
> 
> Why even both installing the Zarrs in the Dandiset datasets in the first place? We could just register them as gitmodules but not check them out there — though I'm not sure how best to do that with DataLad.

sure. Just recall that it is not only about registering as a submodule (within .gitmodules) but also updating that submodule "Subproject commit" (git term in the commit corresponding to commit with submodule hexsha) whenever zarr gets updated to some new state.  So if we can avoid installing it entirely and just keep somehow (didn't look how that is possible) to update submodule without installing it -- then all good, and we will save some inodes on the server ;)

**Comment by yarikoptic** [comment]
FWIW, `git update-index --index-info`, man: https://gitirc.eu/git-update-index.html , seems to be the command to use to update the submodule/subproject state directly avoiding `git add submodule` -- so we could indeed update the subdatasets states without having them installed.

**Comment by yarikoptic** [comment]
FWIW: I have tried and it works.  we just need to commit an  entire (staged) index, without pointing to submodules path:

```
(git-annex)lena:/tmp/openneuro[master]
$> git status; echo '160000 797debeb3bc86400a8bbe3c3d4641285f6fb00c9 0  ds000001' | git update-index --index-info; git diff --cached              
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
diff --git a/ds000001 b/ds000001
index f8e27ac..797debe 160000
--- a/ds000001
+++ b/ds000001
@@ -1 +1 @@
-Subproject commit f8e27ac909e50b5b5e311f6be271f0b1757ebb7b
+Subproject commit 797debeb3bc86400a8bbe3c3d4641285f6fb00c9
(dev3) 1 3161 [1].....................................:Fri 26 Aug 2022 10:48:00 AM EDT:.
(git-annex)lena:/tmp/openneuro[master]
$> git commit -m manual ds000001
error: 'ds000001' does not have a commit checked out
fatal: updating files failed
(dev3) 1 3162 ->128 [1].....................................:Fri 26 Aug 2022 10:48:04 AM EDT:.
(git-annex)lena:/tmp/openneuro[master]
$> git commit -m manual         
[master 0621073] manual
 1 file changed, 1 insertion(+), 1 deletion(-)
```
```

**Comment by jwodder** [comment]
@yarikoptic How would this interact with DataLad?  Would we still be able to use `datalad save`?  Would we need to copy the datalad-id to `.gitmodules` ourselves?

**Comment by yarikoptic** [comment]
- `save` -- good question. I think it would not care about updated index. Asking @mih here "officially" as well: https://github.com/datalad/datalad/issues/6985 . So, I guess, we might need to do manual `git commit` if `datalad save` did nothing, or `git commit --amend` if `datalad save` did save some changes (returned some result records) but did not commit updated submodules in the index.

<details>
<summary>my test case for this where I created new file, save committed it but did not commit updated index, and then I called commit --amend which did commit everythin</summary> 

```shell
(git-annex)lena:/tmp/openneuro[master]
$> datalad --version
datalad 0.17.3+3.g9b2101051
(dev3) 1 3178 [1].....................................:Fri 26 Aug 2022 10:53:12 AM EDT:.
(git-annex)lena:/tmp/openneuro[master]
$> git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   ds000001

(dev3) 1 3179 [1].....................................:Fri 26 Aug 2022 10:58:04 AM EDT:.
(git-annex)lena:/tmp/openneuro[master]
$> touch 123
(dev3) 1 3180 [1].....................................:Fri 26 Aug 2022 10:58:11 AM EDT:.
(git-annex)lena:/tmp/openneuro[master]
$> datalad save -m "saving updated index after creating dummy 123"
add(ok): 123 (file)                                                                                                              
save(ok): . (dataset)                                                                                                            
action summary:                                                                                                                  
  add (ok: 1)
  save (ok: 1)
(dev3) 1 3181 [1].....................................:Fri 26 Aug 2022 10:58:20 AM EDT:.
(git-annex)lena:/tmp/openneuro[master]
$> git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   ds000001

(dev3) 1 3182 [1].....................................:Fri 26 Aug 2022 10:58:26 AM EDT:.
(git-annex)lena:/tmp/openneuro[master]
$> git commit --amend 
[master d406fbd] saving updated index after creating dummy 123
 Date: Fri Aug 26 10:58:20 2022 -0400
 2 files changed, 2 insertions(+), 1 deletion(-)
 create mode 120000 123
(dev3) 1 3183 [1].....................................:Fri 26 Aug 2022 10:59:04 AM EDT:.
(git-annex)lena:/tmp/openneuro[master]
$> git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

```
</details>

- may be we should `install` upon initial addition so datalad does whatever it would want to do and then uninstall and never install it again?

**Comment by yarikoptic** [comment]
https://github.com/datalad/datalad/issues/6985#issuecomment-1228694071 by @jwodder provides more support to do the latter " install upon initial addition so datalad does whatever it would want to do and then uninstall and never install it again"

**Comment by jwodder** [comment]
@yarikoptic What command do you recommend for uninstalling submodules?  I tried `datalad foreach-dataset -s datalad remove`, but that marks the submodules as deleted.

**Comment by yarikoptic** [comment]
`datalad uninstall {subdataset}` (or `datalad drop --what all {subdataset}`) so smth like

```
datalad foreach-dataset -s --cmd-type eval --chpwd pwd 'ds.uninstall(check=False)'
```

`remove` is more like `git rm` which we do not want to do, or even

```
datalad foreach-dataset --jobs 4 -s --cmd-type eval -R 1 --chpwd pwd 'ds.uninstall(check=False, recursive=True)'
```
if to parallelize at the top level while possibly uninstalling nested (we shouldn't have any ATM)
