### ISSUE TITLE
do not log external libs unless we set logging to level < DEBUG (in tests and/or production)

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#259]
tests outputs are flooded with debug logging of pyout, e.g. https://github.com/dandi/dandisets/runs/8232934204?check_suite_focus=true#step:8:6807  but I do not think that pyout logging is unlikely to be relevant to troubleshoot any problems we might encounter in this or dandi code.

**Comment by yarikoptic** [comment]
there is also other loggers which log and I think we should not. I have made /mnt/backup/dandi/dandisets/.git/dandi/backups2datalad/_filterlog_.sh helper

```shell
#!/bin/bash

for l in "$@"; do
        outl="${l//.log/_filt.log}"
        echo $outl
        grep -v  -e '\] \(httpx\|urllib3\|botocore\)' -e "^b'<?xml version=" < "$l" >| "$outl"
done
```

and the difference in size on a still running process log is **very significant**:

```
/mnt/backup/dandi/dandisets/.git/dandi/backups2datalad# ls -l 2022.09.12.19.01.50Z*.log
-rw-r--r-- 1 dandi dandi   484656242 Sep 13 11:41 2022.09.12.19.01.50Z_filt.log
-rw-r--r-- 1 dandi dandi 69959445240 Sep 13 11:42 2022.09.12.19.01.50Z.log

# du -scm 2022.09.12.19.01.50Z*.log
463     2022.09.12.19.01.50Z_filt.log
66891   2022.09.12.19.01.50Z.log
```

may be make those log (at their whatever levels they log) only `if logging.getEffectiveLevel() < 10` so we still could get them if very desired (AFAIK we log at DEBUG into those log files by default).

**Comment by jwodder** [comment]
@yarikoptic Are you talking about logging while testing or while running?  The initial comment is about testing, but your newest comment seems to be referring to the "production" logs.

**Comment by yarikoptic** [comment]
oh, indeed.  I think that generally while setting up logging we should not log any of those external libs unless logging level is set even further below DEBUG.  In tests fixture sets it to DEBUG so we would not log them then in testing.

edit: adjusted the title

**Comment by jwodder** [comment]
@yarikoptic Note that the `--log-level` option only takes log level names, with nothing less than `DEBUG` supported.  Do you want that changed somehow?

Also, should `--log-level` (which controls the logs printed to the screen) have any effect on the logs logged in the log file?

**Comment by yarikoptic** [comment]
If we were to use log levels < 10 it would be probably for the log file.  I would just keep it as is in terms of control of log levels, and if later is needed we could tune DEBUG for log into lower as/if needed.

**Comment by jwodder** [comment]
@yarikoptic I am unable to reproduce pytest's reporting of pyout etc. logs on test failure.

**Comment by yarikoptic** [comment]
interesting. if you run 
```
dandi ls -r -f pyout --metadata assets dandi://dandi/000029@draft/sub-RAT123/sub-RAT123.nwb
```
and look into .log file produced -- do you see all pyout DEBUG entries?
