### ISSUE TITLE
Add --zarr-mode asset-checksum

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#284]
https://github.com/dandi/dandisets/pull/282/files# implements `--mode timestamp` which relies on comparing stored for zarr latest timestamp across all keys for that prefix on S3. While doing a backup of a dandiset with lots of zarrs, that would then entail listing all zarrs contained in that dandiset (could be thousands) on S3 -- too expensive -- even if no asset for those zarrs has changed.  I think we need addition of another mode to use asset's time stamp (present on the server and also stored in .dandi/assets) so we do not sync if the asset for that zarr has not changed  since the last sync of that dandiset.

**Comment by jwodder** [comment]
@yarikoptic You mentioned in Slack that you were concerned about having to store two timestamps per Zarr.  Assuming the "asset modified" timestamp for a Zarr is updated whenever an entry in the Zarr is updated (and I don't know how safe that assumption is), what would be the problem with the code just storing one timestamp per Zarr and using & updating that timestamp based on the current mode?

EDIT: Or do you want this mode to specifically rely on the timestamp stored in `.dandi/assets.json`?

**Comment by yarikoptic** [comment]
> @yarikoptic You mentioned in Slack that you were concerned about having to store two timestamps per Zarr.

I forgot to realize that we already store asset timestamps in `.dandi/assets.json` but recalled that whenever filing this issue.

> Assuming the "asset modified" timestamp for a Zarr is updated whenever an entry in the Zarr is updated (and I don't know how safe that assumption is), what would be the problem with the code just storing one timestamp per Zarr and using & updating that timestamp based on the current mode?

What would it be updated to? Overall smells like that would make it ambiguous on what that timestamp is and thus lead to unexpected behavior: asset's time stamp could change if any metadata change happens etc...  

Anyways -- I think we "concentrated" on S3 in --zarr-mode too much... default mode of operation should lead to decision making solely based on assets metadata and in particular the stored checksum as we do for blobs (checksums from git-annex key, not using asset modified timestamp AFAIK) : so let's make it `--zarr-mode asset-checksum` which
- compare asset timestamp to the one stored for zarr, and if
  - didn't change -- nothing to do (skip the asset, no sync)
- if checksum from server matches the stored, and if
  - didn't change -- nothing to do (skip the asset, no sync)
- proceed to the sync which would do full sync based on listing S3 with ETags and getting local checksums, thus ensuring 1-to-1 correspondence. Note: Updated checksum might get stored locally even if no in-zarr file changes (just signaling that our stored checksum was off).

Then with non-default `--zarr-mode timestamp` we could trigger "lightweight" checking  from S3 based on timestamp, with `checksum` -- a little heavier since we would need to checksum locally, and `force` -- guaranteed to go through.

**Comment by jwodder** [comment]
@yarikoptic The description of the `asset-checksum` mode seems unfinished.  How is the checksum supposed to fit in?

**Comment by yarikoptic** [comment]
> @yarikoptic The description of the `asset-checksum` mode seems unfinished. How is the checksum supposed to fit in?

indeed... I have updated it right in place. Does that look complete?  I feel like it should be the one closest to how we handle regular blob assets by default, and the other modes are more for fixups whenever needed.

**Comment by jwodder** [comment]
@yarikoptic Should the checksum comparison follow the same logic as for the "checksum" Zarr mode (which involves also computing the actual checksum for the files in the Zarr backup)?

> proceed to the sync which would do full sync based on listing S3 with ETags and getting local checksums, thus ensuring 1-to-1 correspondence

Are you simply saying that the sync should be done as in non-"timestamp" mode, i.e., every entry in the Zarr gets synced regardless of that entry's timestamp?

**Comment by yarikoptic** [comment]
> @yarikoptic Should the checksum comparison follow the same logic as for the "checksum" Zarr mode (which involves also computing the actual checksum for the files in the Zarr backup)?

I think so -- it would then provide most "solid" approach -- we should not get to checksum comparison unless we find that zarr level checksums differ (should be rare event) so it is IMHO ok to sacrifice a bit of IO here. Or do you think we should go just for the S3 listing timestamps ?

> > proceed to the sync which would do full sync based on listing S3 with ETags and getting local checksums, thus ensuring 1-to-1 correspondence
> 
> Are you simply saying that the sync should be done as in non-"timestamp" mode, i.e., every entry in the Zarr gets synced regardless of that entry's timestamp?

I think so, unless you say that it is a bad idea.

**Comment by jwodder** [comment]
@yarikoptic I've implemented this as part of #282.
