### ISSUE TITLE
organize https://github.com/dandi-datasets

### ISSUE THREAD

**Issue by satra** [dandi/dandisets#3]
proposed organization:

- [x] each repo is a dandiset
- [x] each repo has a dataset_descriptor.yml (to have comments and readability of multiline strings) with keys from the FAIR dataset doc: https://docs.google.com/document/d/1WvRr9J2Ums0-CQIcdUeFZakE2RPeagRnexUBFDiiV7w/edit?ts=5defc58b
- [x] the entire dandi-datasets is available through datalad

**Comment by satra** [comment]
@yarikoptic - we should do this for the current datasets as a way of figuring out the mechanics externally. then we can consider how to move the mechanics to girder.

**Comment by yarikoptic** [comment]
I think we are done with this one now ;) all of them at https://github.com/dandisets, this repository will provide super dataset and tools for datalad'ification etc.
