### ISSUE TITLE
populate* -- use `annex copy --from ... --to `

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#325]
instead of tandem of `get` and `move --to` as we do now.

Joey has implemented it  https://git-annex.branchable.com/todo/copy_with_both_--to_and_--from_/

I have upgraded git-annex-standalone systemwide on drogon, so if we are ready to deploy before getting fresh version in conda-forge - we just need to uninstall it from `dandisets` conda env:

```
(dandisets) dandi@drogon:~$ which git-annex
/home/dandi/miniconda3/envs/dandisets/bin/git-annex
(dandisets) dandi@drogon:~$ git annex version
git-annex version: 10.20220927-geb4a544
```

**Comment by jwodder** [comment]
@yarikoptic I'm a bit reluctant to implement this right away, as the version of git-annex in Homebrew (which is what I use) is still on 10.20221212, so it'd lead to difficulties with testing the code on my machine.

**Comment by yarikoptic** [comment]
ok, let's mark blocked for now

**Comment by yarikoptic** [comment]
just curious: https://formulae.brew.sh/formula/git-annex says that there is also `HEAD` version. Does it mean `brew` would build from current git HEAD of git-annex?

**Comment by jwodder** [comment]
@yarikoptic I'm not sure, but given that [the upgrade to the latest git-annex in Homebrew is held back by a build error](https://github.com/Homebrew/homebrew-core/pull/121594), I'm not sure building from HEAD would succeed.

**Comment by yarikoptic** [comment]
new annex is in brew now: https://formulae.brew.sh/formula/git-annex

**Comment by jwodder** [comment]
@yarikoptic That's good, but now the tests are failing with a combination of https://github.com/dandi/dandi-archive/issues/1494 and (locally for me, at least) https://github.com/datalad/datalad/issues/7286.
