### ISSUE TITLE
Log log's filename while exiting (specifically on crash)

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#327]
ATM hard to figure out which log corresponds to the run in question.  When program exits, especially on an exception, let's log (so visible to the screen) the filename of the log file.  Could be done with some decorator alike `@map_to_click_exceptions` we have in dandi-cli to be added to all click command line interfaces. or may be there is some other way to centralize at `click` level.

**Comment by jwodder** [comment]
@yarikoptic Note that the path to the logfile is already logged at the start of the run, though it's at `INFO` level and so won't show up on the screen when `-l WARNING` is passed as is done in the shell scripts.  Should that initial log message simply be made more visible, presumably by increasing its log level?

**Comment by yarikoptic** [comment]
> Note that the path to the logfile is already logged at the start of the run

yeah, but quite often if ran "interactively" we have too much of output from datalad etc, so no longer can be observed. That is why we better log it at the end.  I guess it could stay at INFO if there is no failed run, and if there is a failed run - ERROR level.  Initial could stay at INFO. Useful to keep/have in case someone wants to run and right away to follow in the log
