### ISSUE TITLE
check on why there and cleanup dandisets in staging

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#339]
There is up to 7 pages of freshish dandisets from testing 
![image](https://user-images.githubusercontent.com/39889/228542477-ad98f44c-21a7-4362-ab65-d200b919fd97.png)
on staging . Likely from some failing CI test runs -- but shouldn't those be removed/cleaned up anyways?

please clean those up from staging.

**Comment by jwodder** [comment]
@yarikoptic When I search for "backups2datalad" on staging, I only get three pages of results.  All of the Dandisets in question appear to have been created around October 24, 2022, and the CI logs from that time have expired.

**Comment by jwodder** [comment]
Dandisets cleaned up.
