### ISSUE TITLE
backups2datalad.py: RF to use dandi-api not girder

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#36]
migration is upon us, so time to have this script migrate to use dandi-api interface and URLs
- overall scope: replace interactions with girder instance with interactions with dandi-api
  - https://gui-beta-dandiarchive-org.netlify.app/#/dandiset still has some datasets populated so would work, but I think it is worthwhile to:
  - add basic testing on a dockerized instance (setup similar or may be even could reuse dandi-cli ?) where we 
    - create dandiset
    - populate with sample data
    - populate/create datalad dataset
    - update sample dandiset
    - see if update works out as expected
- URLs to add:
  - I think we should populate two URLs:
    - dandi-api endpoint (assets are no longer mutable so should be ok): `/dandisets/{versions__dandiset__pk}/versions/{versions__version}/assets/{asset_id}/download/`
    - direct url to S3 `blobs/` store

Later: 
- I left prior #34 as is for now.  We might handle that one later as "remove girder URLs" script

**Comment by jwodder** [comment]
@yarikoptic Problem: `backups2datalad.py` compares SHA256 hashes reported by the API against SHA256 hashes reported by git-annex in order to determine whether to redownload assets, but the new API doesn't use SHA256, only etags.  As a result, the decision of whether to redownload will be based solely on filesize, which is less reliable.

**Comment by yarikoptic** [comment]
right! well -- we are doomed to recompute it since AFAIK we do not have yet sha256 offband computation (or do we @dchiquito ?).
And since we will be re-uploading all the data from the same box (and with this note -- the same account) we could reuse that cached value - just use the same function we use for computing etag in dandi-cli?

The extra question is either we should rely solely on fscacher to cache it (we have outstanding issue with having some LRU expiration etc), or we could  (ab)use git-annex metadata and store it.  I think let's postpone this later portion and just rely on fscacher.    I might just need to move `/home` on drogon to also reside under /mnt/btrfs so we do not exhaust inodes of `/` again.  Will do some time later today (after we go into read-only and I do final sync and disable cron jobs)

**Comment by satra** [comment]
@yarikoptic - perhaps as part of this transition we can move to blake2/3, one of which i think is supported by git-annex and consolidate towards that. but indeed the whole out of band checksum computation needs to be enabled.

**Comment by jwodder** [comment]
@yarikoptic You're suggesting that, in lieu of getting the SHA256 hash from the API, it instead be calculated by (cached) hashing the source asset in the assetstore?  (I don't know what cached value you're suggesting be reused.)  Then what should happen when there's no asset in the assetstore but there is an asset in the dataset?

**Comment by yarikoptic** [comment]
> @yarikoptic - perhaps as part of this transition we can move to blake2/3, one of which i think is supported by git-annex and consolidate towards that. but indeed the whole out of band checksum computation needs to be enabled.

and most likely we would just still keep sha256 computation out of band... And since we do not have any other checksum computed ATM (other than our dandi-etag), it is all hypothetical.  What we also want to see is that after migration, update of datalad dandisets results in NO CHANGES since it should be exactly that data uploaded.

**Comment by yarikoptic** [comment]
> @yarikoptic You're suggesting that, in lieu of getting the SHA256 hash from the API, it instead be calculated by (cached) hashing the source asset in the assetstore? (I don't know what cached value you're suggesting be reused.)

every asset should have `dandi-etag` ATM (well, after everything is re-uploaded) and we (will) have `blobs/` blob store (ATM it even has some since not yet removed from the bucket) which will be backed up similarly to how we backed up the `girder-assetstore/`.  While considering an annexed file now we cannot just use its `sha256` from key since API does not provide us with sha256 for that asset.  So just call `dandi.support.digests.get_digest(annexed_file, digest="dandi-etag")` for now to get its etag and compare against the one from dandi-api to decide if changed (if size is the same).

> Then what should happen when there's no asset in the assetstore but there is an asset in the dataset?

We will not have `assetstore/` but `blobs/` store. And if an asset is no longer listed for a dandiset by dandi-api, we should remove it in git-annex (I think we do that already).

**Comment by dchiquito** [comment]
@yarikoptic I believe we should actually have a job running to compute the SHA256 of newly minted assets. It isn't used for validation, it's just saved to the asset blob table whenever the job finishes.

Unfortunately I don't see that it is injected into the metadata at the moment, so it's not exposed in the API. I can add that easily if it's required.

**Comment by yarikoptic** [comment]
@dchiquito it would indeed streamline backups2datalad.py operation since then we could just rely on it being provided.

**Comment by dchiquito** [comment]
I don't see a place in the `asset.json` schema where it could be injected. There is a `digest` field, but there is only one. I would assume that we would put the ETag there, since that's the identifier we are using more often.

We could hypothetically put the ETag there if the SHA256 isn't calculated yet, then put the SHA256 after it is computed, but that seems inconsistent and weird. Anything more useful would require a schema modification.

**Comment by satra** [comment]
@dchiquito - you would add another element to digest. the digest field is just a key value store. 

```
  "digest": 
    {"dandi:dandi-etag": "etag value",
      "dandi:sha2-256": "400345830c7f472569753a27e6bb5d1d8e8d49ee78e482a5df6e885a2f64eafc"
    },
```

**Comment by dchiquito** [comment]
I was looking at https://github.com/dandi/schema/blob/master/releases/0.1.0-rc1/asset.json#L1006-L1037, but if that's the case then that should be pretty easy to add. I will see if I can get it tacked on soon.

**Comment by satra** [comment]
latest schema used by the api+ui is here: https://github.com/dandi/schema/tree/master/releases/0.3.0

**Comment by dchiquito** [comment]
FYI https://github.com/dandi/dandi-api/pull/242 should provide all available digests in the asset metadata.
