### ISSUE TITLE
Make backups2datalad configurable

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#373]
Since it is a datalad dataset anyways, logical would be to just (re)use git/cdatalad configuration under `.datalad/config` and specify all necessary options there. Current configuration hardcoded in https://github.com/dandi/dandisets/blob/draft/tools/backups2datalad/consts.py and https://github.com/dandi/dandisets/blob/draft/tools/backups2datalad/config.py#L48

**Comment by jwodder** [comment]
@yarikoptic backups2datalad already supports configuration via the [`backups2datalad.cfg.yaml`](https://github.com/dandi/dandisets/blob/6934374c40db2cba264a5f5401b496207ffa3310/tools/backups2datalad.cfg.yaml) file.  What further configuration do you want?

**Comment by yarikoptic** [comment]
ah, may be nothing then, let's see what demand would be
