### ISSUE TITLE
add dandiset_id and asset_id into a message

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#49]
I am trying to minimize amount of logging and thus set logger to WARNING level

see only
```
[WARNING ] backups2datalad.py Asset metadata does not include sha256 hash
```
would be nice if it listed dandiset and asset id and/or path.  Even though might grow long -- would be informative on its own

**Comment by jwodder** [comment]
@yarikoptic Dandiset ID and asset path added to warning messages in #48.

**Comment by yarikoptic** [comment]
eh, ok, you really want me to try out that PR ;-)

**Comment by yarikoptic** [comment]
we merged that PR, and I reminded dandi-api folks that issue persists: https://github.com/dandi/dandi-api/issues/254  .  Nothing more to be done here
