### ISSUE TITLE
take commit date as the latest from prior commit date  AND added assets

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#51]
going back in time makes little sense and seems to manage to happen when code starts to invalidate some assumptions as happened for 000055 after bolting on update of assets which caused some assets to be first removed, and then readded in subsequent commit, and making that commit date to be the one of added assets.

**Comment by jwodder** [comment]
@yarikoptic To be clear: When generating updated metadata for assets, you want `dateModified` (or `blobDateModified`?) to be set to the timestamp of the most recent commit of the dataset if it's later than the default value.  Is that what you're saying?

**Comment by jwodder** [comment]
@yarikoptic Disregard the above; what you actually want is for the date of the commit when saving the updated data to be no earlier than the date of the previous commit, correct?  When regenerating asset metadata, should the new `dateModified` also be taken into account?

**Comment by yarikoptic** [comment]
> @yarikoptic Disregard the above; what you actually want is for the date of the commit when saving the updated data to be no earlier than the date of the previous commit, correct? 

yes!

> When regenerating asset metadata, should the new `dateModified` also be taken into account?

I think we should just move out all this regeneration/update of assets into an independent script.  @satra had one cooking yesterday, and then remove that portion of the code here
