### ISSUE TITLE
Prepare dandisets releases

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#54]
Publishing is near. Staging has examples with published dandisets and could be used to test development.

I am thinking we should add
- a function and CLI end point to create a release . It would get a release string, and an optional commitish based on which to create a release (possibly with an extra commit if list of assets differs in the released on dandi dandiset). 
   - if no commitish provided - look through history to find a commit with identical list of assets. If none found - error
   - it would create/push annotated git tag
   - not sure yet if worth creating GitHub releases for them, since GitHub isn't the place where releases are minted
- when a new (not yet tagged) release added to archive, call above function

**Comment by jwodder** [comment]
@yarikoptic 

> possibly with an extra commit if list of assets differs in the released on dandi dandiset

What exactly would this "extra commit" be used for?  If the assets differ between the repo and the Dandiset, why not just pass the commitish for when they matched?  Or do you mean that, if the repo is behind the Dandiset, it should update and commit the metadata?  I think doing that should be taken care of by the pre-existing portion of `backups2datalad.py` rather than be added to this function.

**Comment by jwodder** [comment]
@yarikoptic Also, what should the tag message be for the annotated tags?

**Comment by jwodder** [comment]
@yarikoptic Also, what exactly do you want the syntax of the CLI command to look like?  The most natural option would be to make it a subcommand, but that would require converting the functionality of the current `backups2datalad.py` command to a subcommand as well.

**Comment by yarikoptic** [comment]
Since we have only a single point of deployment it would easy to convert the invocation.

While at it may be let's rename it into `datalad-dandisets` command may be?  With commands (names are tentative -- if you think of better ones, I would not mind)
- `update-from-backup ...` (current `backups2datalad.py`; can change CLI interface to harmonize if so desired etc)
- `release [--commitish COMMITISH] [-d DANDISET_PATH] VERSION` (defaulting to current directory dandiset)

**Comment by jwodder** [comment]
@yarikoptic Should the `update-from-backup` procedure ever invoke `release`?  As far as I can tell, the only way to check for new published versions is to fetch all of them and compare them against the repo's tags.

**Comment by yarikoptic** [comment]
> @yarikoptic Should the `update-from-backup` procedure ever invoke `release`? 

yes, it should as it would be ran by a cron job and ideally (unless we run into those cases where we can't deduce what release is based on) it should be automated

> As far as I can tell, the only way to check for new published versions is to fetch all of them and compare them against the repo's tags.

or, assuming that we do not release/delete-release/re-release-under-the-same-version, just fetch `/dandisets/{dandiset__pk}/versions/`, and analyze those for which we do not yet have a git tag.
