### ISSUE TITLE
move to use "draft" (not "master") branch

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#57]
"master" branch is now frowned upon, and carries no semantic meaning in DANDI land.

- code need to create/set  on github "draft" branch to be the default one
  - should be done after #55 is merged (auto-testing is blocked ATM waiting for staging bucket to become more public), thus this issue `blocked` for now
  - will need a helper command to adjust default branch of all dandisets on github already
- on drogon
  - disable cron job
  - rename "master" to draft on drogon on all of local copies
  - run the helper command to adjust github clones
  - re-enable cron job

**Comment by yarikoptic** [comment]
Let's do that now, while we are still distilling down the solution for handling the releases/tagging/authors anyways and service is not "live" ATM.

**Comment by jwodder** [comment]
@yarikoptic When creating a dataset with `ds.create()`, how do I set the initial/default branch to "draft"?

**Comment by yarikoptic** [comment]
try smth along the lines of 

```
    set_envvar("GIT_CONFIG_PARAMETERS",
               "'init.defaultBranch={}'"
               .format("draft"))
```

**Comment by jwodder** [comment]
@yarikoptic I've updated the default branch for the currently-existing datasets, but I'm holding off on re-enabling the cronjob until after #72 is merged, as it alters the default branch for newly-created datasets.

**Comment by jwodder** [comment]
Cronjob re-enabled.

**Comment by yarikoptic** [comment]
cool, I guess you mean
```
12 * * * * chronic flock -E 0 -e -n /home/dandi/.run/backup2datalad-cron.lock bash -c '/mnt/backup/dandi/dandiarchive-s3-backup.sh
```
? this one is just a backup from s3 , not triggering all the backups2datalad business which I disabled after originally these instructions were written I believe -- it is one commented out above this one.  We will enable it later.

I also wonder if we should switch `dandisets` itself to `draft` since all commits it would be pointing to, would be the "draft" branches too... I think I will do that but after #73 (and anything else which pops up) merged so we are not dancing between branches in PRs etc.

**Comment by yarikoptic** [comment]
all PRs are merged, will rename master to draft in this repo as well now, do more testing, and then if all looks kosher -- reenable cron job. Thank you @jwodder for all the work

**Comment by yarikoptic** [comment]
we are done with this -- all systems are "deployed", and https://github.com/dandi/dandisets/ is regularly updated in its `draft` branch
