### ISSUE TITLE
seems to be choosing "prior" (wrong) commit to git tag for a release

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#58]
Testing on 000003 (was pushed to https://github.com/dandisets/000003 a few hours back).

When I ran 

```
flock -E 0 -e -n /home/dandi/.run/backup2datalad-cron.lock bash -c '/mnt/backup/dandi/dandisets/tools/backups2datalad-cron 000003'
```

on drogon, it produced a tag, which was not pushed (should have been I guess),  which I now pushed (we can delete later) which points to prior commit
```
dandi@drogon:/mnt/backup/dandi/dandisets/000003$ git show 0.210812.1448 | head 
tag 0.210812.1448
Tagger: DANDI Meta-user <dandi@mit.edu>
Date:   Thu Aug 12 14:48:34 2021 -0400

Version 0.210812.1448 of Dandiset 000003

commit 30680bd1657172824c64e83eac8f02cb33307897
Author: DANDI Meta-user <dandi@mit.edu>
Date:   Tue Aug 10 03:16:35 2021 -0400
```
where metadata didn't have `publishedBy` for assets yet... 

Even after I removed tag and reran -- consistently was tagging that commit instead of the last one which either should be the one, or an off-master commit with the "state" of that particular release being there.

<details>
<summary>I have not done full comparison of the state of assets, but first page is identical ;)
</summary> 

```shell
$> curl --silent -X GET "https://api.dandiarchive.org/api/dandisets/000003/versions/0.210812.1448/assets/" -H "accept: application/json" | jq . > /tmp/published.json
1 13330.....................................:Thu 12 Aug 2021 02:58:22 PM EDT:.
lena:/tmp
$> curl --silent -X GET "https://api.dandiarchive.org/api/dandisets/000003/versions/draft/assets/" -H "accept: application/json" | jq . > /tmp/draft.json  
1 13331.....................................:Thu 12 Aug 2021 02:58:34 PM EDT:.
lena:/tmp
$> md5sum /tmp/draft.json /tmp/published.json
e78164fb26c166fe7711867fd7b8483c  /tmp/draft.json
f5b964485a06f5c09adc8295167b1e18  /tmp/published.json
1 13332.....................................:Thu 12 Aug 2021 02:58:39 PM EDT:.
lena:/tmp
$> diff /tmp/draft.json /tmp/published.json  
3c3
<   "next": "https://api.dandiarchive.org/api/dandisets/000003/versions/draft/assets/?page=2",
---
>   "next": "https://api.dandiarchive.org/api/dandisets/000003/versions/0.210812.1448/assets/?page=2",

```
</details>

and clearly that prior commit didn't have matching listing of assets since back then there were no publishedBy.

PS I will disable autodataladification until this is addressed

**Comment by yarikoptic** [comment]
> Is `ds.push(to="github", jobs=self.jobs)` supposed to push tags?

for a remote it pushes what is configured to be pushed for that remote (at git level)... long story short - probably best would be to just follow up with with an explicit `ds.repo.call_git(['push', *new_tags])` or alike, so we do not resort to pushing all tags.

**Comment by yarikoptic** [comment]
> As for the tagging of the "prior commit",  

I will check in greater detail in a minute, but it seems that we 

- need to consider two commits -- right before and right after (yet to see what we use for commit date and how what we observed could happen)
- assets metadata **must** be compared as well
   - if any matches exactly -- that is the commit (if both match somehow, shouldn't happen -- assert!)
   - if none matches -- create release branch off the commit before the release

**Comment by yarikoptic** [comment]
right... we can't rely on the commit date as the sole filter in 
```
            commitish = readcmd(
                "git",
                "rev-list",
                f"--before={dandiset.version.created}",
                "-n1",
```
and we tune those to correspond, both AUTHOR and COMMITTER... sent out https://github.com/dandi/dandisets/pull/62 to set only AUTHOR.  Also I am not sure even if we were setting it correctly

```
$> curl --silent https://api.dandiarchive.org/api/dandisets/000003/versions/ | jq -r '.results[] | "\(.created) \(.modified) \(.version)"'
2020-03-15T22:56:55.655000Z 2021-08-12T14:48:45.203390Z draft
2021-08-12T14:48:45.032118Z 2021-08-12T14:48:45.186427Z 0.210812.1448

$> git -C /tmp/000003 log --date=iso8601-strict --format="%ad %cd %h %(describe)" | head -n 4                                             
2021-08-12T11:17:15-04:00 2021-08-12T11:17:15-04:00 f2da8ee 0.210812.1448-1-gf2da8ee
2021-08-10T03:16:35-04:00 2021-08-10T03:16:35-04:00 30680bd 0.210812.1448
2021-08-05T15:17:25-04:00 2021-08-05T15:17:25-04:00 ab67941 
2021-08-02T11:19:34-04:00 2021-08-02T11:19:34-04:00 b7efdf8 
```
so the  f2da8ee got commit for 11:17:15-04:00 which would be 15:17:15Z although `modified` for draft still is 14:48:45.203390Z (and previous commit is days back) -- so may be whatever was set was not in effect (can reset --hard on a throw away clone and troubleshoot from there)
 
note: with `--before` we might also miss the commit which happened EXACTLY on the same datetime, which then asks also for considering a commit right after that to include possible exact match.

**Comment by yarikoptic** [comment]
> assets metadata **must** be compared as well
> * if any matches exactly -- that is the commit (if both match somehow, shouldn't happen -- assert!)
> * if none matches -- create release branch off the commit before the release

clarification: since released dandiset metadata (dandiset.yaml) should carry `doi` and `publishedBy` fields, whenever `draft` not, all release tags should reside on dedicated release commits (temporary branches, tagged) , so in above in both cases release tag should not be on the main branch, but off one of those commits

**Comment by yarikoptic** [comment]
above comes with "cons" of `git describe` (which I really like) being defunc in such dandisets. In principle we can establish merges back into the main tree of all unmerged releases (or even rewriting not yet pushed history to make it better) while taking main branch tree as the target (so nothing really merged), but I do not think yet this game/ugliness is worth the candles.

**Comment by jwodder** [comment]
@yarikoptic Given that many commits don't have their dates set correctly, how exactly should the search for a matching commit work?

**Comment by yarikoptic** [comment]
I wouldn't sweat about it for those which didn't have correctly -- let's do our "best attempt", as I described in https://github.com/dandi/dandisets/issues/58#issuecomment-897936936  -- consider two commits (or whatever the number of direct kids that commit got on the main branch), and choose one with matching assets, if none -- choose the later one.  In either case we need an off-master branch commit.  The main point is to tag a correct "state" of the dandiset, so all assets are as in release, and dandiset.yaml is also as in the release.
