### ISSUE TITLE
dandi:000017 metadata discrepancy

### ISSUE THREAD

**Issue by satra** [dandi/dandisets#6]
@bendichter  - is this: https://dandiarchive.org/dandiset/000017/ the same as this: https://figshare.com/articles/dataset/Eight-probe_Neuropixels_recordings_during_spontaneous_behaviors/7739750

if so we should change the license, and also point to that resource. 

we may want to make the changes after the publish ui is merged, but wanted to note the discrepancy.

**Comment by yarikoptic** [comment]
while we do not have "issue reporting" on dandiarchive.org, should we then see to enable Issues on individual dandisets on https://github.com/dandisets ?  Then we can (ab)use github to provide our dandisets overall issue tracking (datalad or not related).

**Comment by bendichter** [comment]
@satra Yes, I believe it is, and @yarikoptic yes, using dandisets to organize these types of things seems like a good idea

**Comment by yarikoptic** [comment]
Great, closing this one, #8 (and referenced there datalad origin fix) will introduce Issues
