### ISSUE TITLE
Do needed dances in github CI to get things installed

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#61]
libhdf5 fights back, see runs for https://github.com/dandi/dandisets/pull/59

**Comment by jwodder** [comment]
Already handled by #60.  The remaining failure is because I'm pushing from a fork and so the action doesn't have access to the `DANDI_API_KEY` secret.

**Comment by yarikoptic** [comment]
next one is 
```
 git-annex of version >= 7.20190503
```
as can be seen in https://github.com/dandi/dandisets/pull/62
