### ISSUE TITLE
backups2datalad.py: Address TODOs

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#7]
See https://github.com/dandi/dandisets/blob/master/tools/backups2datalad.py#L15 (note: I added raise of an exception just to avoid myself running it ATM)

@jwodder you should be able to login as `dandi` to drogon.  This superdataset is at `/mnt/backup/dandi/dandisets` but if any development/testing to be done, we better do it elsewhere OR on `000029` which is our "development" beast we can torture

**Comment by jwodder** [comment]
@yarikoptic What exactly does "make work with released datalad (so return back special remote setup helpers)" mean?  Note that the code currently requires [a version of datalad that hasn't even been merged yet](https://github.com/datalad/datalad/pull/5065); do you want me to undo taking advantage of that PR and call `init_remote` the old/currently-supported-by-released-datalad way?

**Comment by yarikoptic** [comment]
> * What exactly does "make work with released datalad (so return back special remote setup helpers)" mean?  Note that the code currently requires [a version of datalad that hasn't even been merged yet](https://github.com/datalad/datalad/pull/5065); do you want me to undo taking advantage of that PR and call `init_remote` the old/currently-supported-by-released-datalad way?

yes, for now pretty much revert https://github.com/dandi/dandi-cli/commit/695999079d07faec4cdd49766df2b0091d6a0cb7 . I am yet to review that PR and others would need to chime in, API might change etc.  For running this script we should use released (or maint, and less preferably `master`) version of datalad to avoid surprises etc.

> * By "do not push in here, push will be outside upon success of the entire hierarchy", do you simply mean that the script itself shouldn't perform any pushes?  No other change?

well it is a "maybe", not yet certain of it... keep pushing as is for now.  The idea was: if any dandiset "update" fails, it is an abnormal situation, and we better introspect/analyze/mitigate and then push.  If there is no pushing here, it could be easily accomplished via e.g. `datalad run -m "CRON update job" -d . -J10 tools/backups2datalad.py && datalad push -r -J10`.  I guess all those actions could be contained in the script, so it is just "maybe" for now.

> * What exactly is this "superdataset", and what would it mean for the script to be "aware" of it?

this repository is a DataLad superdataset since it "contains" (as git submodules) all datalad dandisets backups2datalad.py script created or updated. Anyways -- that is "Later" and somewhat "maybe".  I am thinking that may be this script should just work on per-dandiset and the rest would be done outside (e.g. we could parallelize via `datalad foreach` (https://github.com/datalad/datalad/issues/749)) without coding it in.

**Comment by jwodder** [comment]
@yarikoptic Do I need to do anything for the "return back special remote setup helpers" bit?

**Comment by yarikoptic** [comment]
> @yarikoptic Do I need to do anything for the "return back special remote setup helpers" bit?

it think that just revert of https://github.com/dandi/dandi-cli/commit/695999079d07faec4cdd49766df2b0091d6a0cb7 would be enough.

**Comment by jwodder** [comment]
@yarikoptic Done: #12
