### ISSUE TITLE
fully delete test dandisets from dandi-staging upon completion

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#74]
https://github.com/dandi/dandi-api/pull/480 was merged, we use my key ATM on github, so we should be able to proceed and properly cleanup after ourselves upon completion of the test (regardless of the outcome) since by now we amassed a good number (probably majority) among all 120 present there.

- also need to cleanup (separate script/invocation) already existing dandisets (you are admin there @jwodder so should work)
- in principle deletion (upon some explicit `delete_versions=True`) support could be added to dandi-cli itself, but for now I guess could be just done here

**Comment by jwodder** [comment]
@yarikoptic Dandisets on staging cleaned up.

**Comment by jwodder** [comment]
Test Dandisets on staging deleted.
