### ISSUE TITLE
Switch to use "/assets/{id}/download/" url instead of draft-specific asset id based one

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#78]
in https://github.com/dandi/dandisets/blob/draft/tools/backups2datalad.py#L263 we use
```
                download_url = a.download_url
```
and that `RemoteAsset` .download_url is bound to that specific (which is "draft") version of the dandiset, e.g.

```
(Pdb) p self
RemoteAsset(client=<dandi.dandiapi.DandiAPIClient object at 0x7ff60a22ef40>, identifier='5956a8b1-6cde-4ab4-ac2b-a49da0f33373', path='testing/simple1.nwb', size=17352, modified=datetime.datetime(2021, 8, 26, 19, 21, 23, 266781, tzinfo=datetime.timezone.utc), dandiset_id='000001', version_id='draft')
*(Pdb) p self.download_url
'http://localhost:8000/api/dandisets/000001/versions/draft/assets/5956a8b1-6cde-4ab4-ac2b-a49da0f33373/download/'
```
Assets mutate in "draft" rendering those URLs eventually obsolete even if that asset was e.g. published in some version.  That causes git-annex to try first a URL which no longer there, datalad keeps flooding log with error upon each progress update (discovered while giving live demo today, uff... yet to fix in datalad), while still eventually downloading it just fine directly from the 2nd (direct blob on s3) URL.

I first thought to just "fix" RemoteAsset.download_url to just get top `/assets`  url instead of the dataset bound, but decided that it might break some consistency in the design here.  I will leave it for you @jwodder to decide.

alternative could be also to just somehow get a `BaseRemoteAsset` instance for that asset (there is no casting down right) which would provide top level download_url .

and yet another alternative -- just to get those all urls directly from metadata record which carries them both
```
$> curl --silent https://api.dandiarchive.org/api/dandisets/000029/versions/draft/assets/689d7c0c-d980-462e-9a56-3df87efc9658/ | jq .contentUrl
[
  "https://api.dandiarchive.org/api/assets/689d7c0c-d980-462e-9a56-3df87efc9658/download/",
  "https://dandiarchive.s3.amazonaws.com/blobs/c40/57c/c4057c5e-7af5-4370-878f-ccfc971aeba4"
]
```
although with that in mind -- may be `RemoteAsset.download_url` should be "fixed" to not use dandiset bound URL since IMHO there is no advantage.

WDYT @jwodder -- which way should we go?

**Comment by jwodder** [comment]
@yarikoptic I'm thinking that `download_url` should be kept as-is for `RemoteAsset`s and removed from `BaseRemoteAsset`s, and a `base_download_url` property should be added to both that uses `/assets/{id}/download/`.

**Comment by yarikoptic** [comment]
ok, sounds good, please implement in dandi-cli and then use it here.  I somewhat dislike proliferation of those *download_url's but that would indeed nicely reflect the situation (we do have multiple endpoints).
