### ISSUE TITLE
Rewrite all draft dandiset_version bound URLs in git-annex to be top level /assets

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#79]
We better first fix population of those urls (#78) , and then sweep through all existing datalad datasets and replace prior dataset version bound with top level like

```
https://api.dandiarchive.org/api/dandisets/000029/versions/draft/assets/aef92c1b-bee4-41b3-8496-5e50ca370716/download/
```
to top level
```
https://api.dandiarchive.org/api/assets/aef92c1b-bee4-41b3-8496-5e50ca370716/download/
```

So we need a new command `tools/backups2datalad.py make_asset_urls_top_level [DATASETS]` which would `unregisterurl` / `registerurl` .

- I think `git annex whereis --all --json` provides us with the list of  all (not only pointed by HEAD) known keys and their urls. So `/versions/draft/assets` urls should be replaced with corresponding top level ones
- these invocations to unregister/register url should be done with `'-c', 'annex.alwayscommit=false'` and then some annex command issued to trigger a singular commit which would commit all the changes.

**Comment by jwodder** [comment]
@yarikoptic Why does this need to be a `backups2datalad.py` subcommand?  I don't see how it'll use the required global options `--assetstore` and `--target`.

**Comment by yarikoptic** [comment]
Doesn't have to be. I just thought it would be logical to collect all related support functionality as commands of that script.

**Comment by jwodder** [comment]
@yarikoptic I'm finding it simpler to do this via the Datalad API rather than by calling git-annex directly.  Is passing `batch=True` to `ds.repo.add_url_to_file()` (`rm_url()` doesn't have a `batch` option) the proper equivalent of `'-c', 'annex.alwayscommit=false'`?

**Comment by yarikoptic** [comment]
Ok. I think it should be. Just check on a sample dandiset other history of git-annex branch if or results in expected single commit. Not sure if we have interfaced unregisterurl though
