### ISSUE TITLE
script to enable/disable github features across dandisets we already have

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#8]
ATM I would like to 
- disable pull requests (these are "consumables" from dandiarchive, so nothing really should be introduced via PRs)
- disable wikis
- enable issues

I filed related https://github.com/datalad/datalad/issues/5071 to do it at the `datalad create-sibling-github` level.  Well, ideally we should have some helper in datalad `siblings` but that one is "github unaware" ATM. @jwodder -- it could also be just a quick script on top of your github helper may be?  I hope we will just have  https://github.com/datalad/datalad/issues/5071 fixed properly soon, so we would not need to really "redo" it often

**Comment by satra** [comment]
ok for now.

**Comment by yarikoptic** [comment]
what are you thinking about "longer term" @satra ?
