### ISSUE TITLE
Allow for archive to grow without filling up drogon

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#84]
soon poor drogon will not be able to afford keeping the backup of the entire archive. I see two possible ways

### 1 drop "old" content

we could just start dropping some (if not most) old content from the "girderarchive" and all dandisets, and `get` it only if needed (withing the large "girderarchive"), and do the same what we did before otherwise.

I think this would be the easiest way although might need to check if that s3cmd invocation we use to possibly "correct" for the screw ups of datalad-crawler.  If we drop - content, will need to check that s3cmd "backing up" would work out correctly.  If it does -- then I think we should be all good.

### 2 RF to operate without "girder/blobs store" backup, purely on metadata

- RF to operate without "girder/blobs store" backup, purely on metadata.  backups2datalad.py would really be operating without "backups" and not backup the actual content. We would just take care about removing old files and just mint target paths/annex-keys based on metadata (since we used SHA256E backend - we should be ok)

**Comment by yarikoptic** [comment]
ok, I think we should just proceed with `1+2 = 3`:

# 3 RF to operate without "girder/blobs store" backup, still downloading/backing up to special remote

- stop using `girderarchive` : so we will not be backing up the entire bucket but only the dandisets and their assets . So no `datalad crawl` nor `s3cmd` fixups
- adjust our backups2datalad.py so 
  - for a new asset:
    -  if not yet known to that given datalad dataset git-annex key/checksum -- download the file from dandiarchive/S3 (instead of `cp --reflink` from `girderarchive`)
    - if key is known to git-annex, just create a new file/symlink pointing to that known annex key, no download is needed
       -  if not present in `dandi-dandisets-dropbox` (provided in `backup_remote`) annex special remote -- issue a warning (ideally should check if it is just not a duplicate asset which was already just added under another path but was not yet pushed to dropbox)
- after `push`ing to `backup_remote`, drop content locally (yes, we will no longer have a usable copy, but datalad-fuse will come to help ;)): `git annex drop --in dandi-dandisets-dropbox` 

I think this should work, since I do not expect a single run to be "too large" to not fit in available free space and we would be dropping right after completion.

@jwodder am I may be missing some aspect?

**Comment by jwodder** [comment]
@yarikoptic

* I'm assuming that the git-annex key for an asset can be calculated from just the metadata with `f"SHA256E-s{asset_size}--{sha256_digest}.{extension}"`; is that correct?
* Aren't the SHA 256 hashes in metadata filled in by a background process on dandi-api?  If so, isn't it possible for a recently-uploaded asset to lack a SHA 256 digest in its metadata?  How should that be handled?
* The datasets are created with `text2git` enabled, which means that we always have to download text-file assets, as they're not stored in git-annex.  How can/should such assets be identified?  By file extension?

**Comment by yarikoptic** [comment]
> * I'm assuming that the git-annex key for an asset can be calculated from just the metadata with `f"SHA256E-s{asset_size}--{sha256_digest}.{extension}"`; is that correct?

yes, but
- extension "algorithm", ref: https://github.com/datalad/datalad/pull/5861 , is not "trivial"
- ideally we should just make git-annex "mint" a key for us, so please check on how to do that using `examinekey`, as done e.g. within https://github.com/datalad/datalad/blob/HEAD/datalad/local/addurls.py#L882 (might need freshish git-annex, forgot when joey added support for that, but it was recent/this year)


> * Aren't the SHA 256 hashes in metadata filled in by a background process on dandi-api?  If so, isn't it possible for a recently-uploaded asset to lack a SHA 256 digest in its metadata?  How should that be handled?

great point.  I thought about "easy way out": just skip that dandiset until all assets have sha256.  But that might be prohibitive etc, since e.g. if active uploads going on, we might end up needing to download all uploaded (>50TB) assets, thus running out of space etc.  We could "copy to backup && drop" for each asset as we go I guess, but still we would be delaying getting any "datalad" view of the dandiset which would be suboptimal.

Thus what about
- given list of new assets to consider, sort by their creation date, choose the latest one which still has sha256 -- consider only those (all new assets with sha256 before/including that latest one)
- .dandi/assets.json dump could be either
   - complete but then we would need to compare to the state of the file tree to see which assets were not downloaded in the prior run
   - exclude assets which we do not download (because they either lack sha256 or some other assets with earlier creation date lacks sha256)
     - if a newer asset (which we are not to download in this run) is to replace an existing asset, we do not "replace" at that point, and keep original asset in place and take its record to be included within assets.json dump
- I am leaning to the latter - since then we can provide "consistent" to that latest created asset date "view" of dandiset
  - git history could come out quite cool for such lengthy uploads, showing the evolution of the dandiset as more assets are uploaded
- If the `created` date among assets which we are not to download is let's say older than a day ago -- we need to error out so we could clarify with dandi-api folks on why its checksum is not yet computed (might need more fixing/tuneup on dandi-api backend side) 

> * The datasets are created with `text2git` enabled, which means that we always have to download text-file assets, as they're not stored in git-annex.  How can/should such assets be identified?  By file extension?

I don't think we need to do anything special here.  So -- those assets will (likely) not have a key in annex, thus we will download them and `datalad save` and they would end up in git as they should.  The only tricky case would be if somehow in the past we have managed to stick that asset content into annex (instead  of git) and thus there would be a known git-annex key for that content, we will end up creating an annexed symlink.  But I do not expect us to run into such cases.

**Comment by jwodder** [comment]
@yarikoptic 

> ideally we should just make git-annex "mint" a key for us, so please check on how to do that using `examinekey`, as done e.g. within https://github.com/datalad/datalad/blob/HEAD/datalad/local/addurls.py#L882

`examinekey` appears to be for getting information for a key that you already have, and I don't see anything in the linked code for minting a key, nor can I find any git-annex subcommands for computing a key without already having the entire file.

**Comment by yarikoptic** [comment]
so give it some "not exactly the right key", e.g. sha256 one (for which you have all the information):

```
(git)lena:~datalad/datalad-extensions[bf-pypi]git
$> echo SHA256-s123--52535c43fa4f6dc66b55f0cecb10519ded6be8fb9780f9b1bef365d08e041ce6 | git annex examinekey --filename blah.txt.gz --migrate-to-backend=SHA256E --batch
SHA256E-s123--52535c43fa4f6dc66b55f0cecb10519ded6be8fb9780f9b1bef365d08e041ce6.txt.gz

```

or the entire path:
```
$> echo SHA256-s123--52535c43fa4f6dc66b55f0cecb10519ded6be8fb9780f9b1bef365d08e041ce6 | git annex examinekey --filename blah.txt.gz --migrate-to-backend=SHA256E --batch --format='${objectpath}/${key}/${key}\n' 
.git/annex/objects/5F/9f/SHA256E-s123--52535c43fa4f6dc66b55f0cecb10519ded6be8fb9780f9b1bef365d08e041ce6.txt.gz/SHA256E-s123--52535c43fa4f6dc66b55f0cecb10519ded6be8fb9780f9b1bef365d08e041ce6.txt.gz/SHA256E-s123--52535c43fa4f6dc66b55f0cecb10519ded6be8fb9780f9b1bef365d08e041ce6.txt.gz/SHA256E-s123--52535c43fa4f6dc66b55f0cecb10519ded6be8fb9780f9b1bef365d08e041ce6.txt.gz
```


note that with "--batch" you could keep feeding it with new entries, thus making it more speedy.  We have a helper `BatchedAnnexes` in datalad if you decide to use that one instead of coding yourself.

**Comment by jwodder** [comment]
@yarikoptic 

* How do I check whether a key is known to git-annex?  None of the commands seem to cover this.
* How do I check whether a key is present in `dandi-dandisets-dropbox`?  Do I do `git-annex checkpresentkey $KEY dandi-dandisets-dropbox`/`annexrepo.is_available(key, remote="dandi-dandisets-dropbox", key=True)`?

> given list of new assets to consider, sort by their creation date, choose the latest one which still has sha256 -- consider only those (all new assets with sha256 before/including that latest one)

Do you mean that you only want to consider the longest initial (by creation date) sequence of assets all with SHA256 digests?

**Comment by yarikoptic** [comment]
> * How do I check whether a key is known to git-annex?  None of the commands seem to cover this.

could be `git annex whereis --batch-keys --json` (seems to need most recent `8.20210903`, updated in dandi@drogon `dandisets` conda env) and ignore exit code which seems to be non-0 if some key  is not known:

<details>
<summary>example</summary> 

```shell
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/000027/sub-RAT123$ echo 'SHA256E-s18792--1a765509384ea96b7b12136353d9c5b94f23d764ad0431e049197f7875eb352c.nwb
> SHA256E-s18792--1a765509384ea96b7b12136353d9c5b94f23d764ad0431e049197f7875eb352c
> SHA256E-s18792--1a765509384ea96b7b12136353d9c5b94f23d764ad0431e049197f7875eb352c.nwb' | git annex whereis --batch-keys --json
{"command":"whereis","note":"2 copies\n\t00000000-0000-0000-0000-000000000001 -- web\n \t4ca7c743-c5d4-4e57-8ba7-ca3dc579591d -- dandi@drogon:/mnt/backup/dandi/dandisets/000027 [here]\n\nThe following untrusted locations may also have copies:\n\t727f466f-60c3-4778-90b2-b2332856c2f8 -- [dandi-dandisets-dropbox]\n\nweb: https://api.dandiarchive.org/api/assets/ff453f4c-a435-4a5d-a48b-128abca5ec47/download/\nweb: https://dandiarchive.s3.amazonaws.com/blobs/2db/af0/2dbaf0fd-5003-4a0a-b4c0-bc8cdbdb3826?versionId=4BMLdtv04lfi7JDWFfUleHVzYazeFVL4\n","success":true,"input":["SHA256E-s18792--1a765509384ea96b7b12136353d9c5b94f23d764ad0431e049197f7875eb352c.nwb"],"untrusted":[{"here":false,"uuid":"727f466f-60c3-4778-90b2-b2332856c2f8","urls":[],"description":"[dandi-dandisets-dropbox]"}],"key":"SHA256E-s18792--1a765509384ea96b7b12136353d9c5b94f23d764ad0431e049197f7875eb352c.nwb","whereis":[{"here":false,"uuid":"00000000-0000-0000-0000-000000000001","urls":["https://api.dandiarchive.org/api/assets/ff453f4c-a435-4a5d-a48b-128abca5ec47/download/","https://dandiarchive.s3.amazonaws.com/blobs/2db/af0/2dbaf0fd-5003-4a0a-b4c0-bc8cdbdb3826?versionId=4BMLdtv04lfi7JDWFfUleHVzYazeFVL4"],"description":"web"},{"here":true,"uuid":"4ca7c743-c5d4-4e57-8ba7-ca3dc579591d","urls":[],"description":"dandi@drogon:/mnt/backup/dandi/dandisets/000027"}],"error-messages":[],"file":null}
{"command":"whereis","note":"0 copies","success":false,"input":["SHA256E-s18792--1a765509384ea96b7b12136353d9c5b94f23d764ad0431e049197f7875eb352c"],"untrusted":[],"key":"SHA256E-s18792--1a765509384ea96b7b12136353d9c5b94f23d764ad0431e049197f7875eb352c","whereis":[],"error-messages":[],"file":null}
{"command":"whereis","note":"2 copies\n\t00000000-0000-0000-0000-000000000001 -- web\n \t4ca7c743-c5d4-4e57-8ba7-ca3dc579591d -- dandi@drogon:/mnt/backup/dandi/dandisets/000027 [here]\n\nThe following untrusted locations may also have copies:\n\t727f466f-60c3-4778-90b2-b2332856c2f8 -- [dandi-dandisets-dropbox]\n\nweb: https://api.dandiarchive.org/api/assets/ff453f4c-a435-4a5d-a48b-128abca5ec47/download/\nweb: https://dandiarchive.s3.amazonaws.com/blobs/2db/af0/2dbaf0fd-5003-4a0a-b4c0-bc8cdbdb3826?versionId=4BMLdtv04lfi7JDWFfUleHVzYazeFVL4\n","success":true,"input":["SHA256E-s18792--1a765509384ea96b7b12136353d9c5b94f23d764ad0431e049197f7875eb352c.nwb"],"untrusted":[{"here":false,"uuid":"727f466f-60c3-4778-90b2-b2332856c2f8","urls":[],"description":"[dandi-dandisets-dropbox]"}],"key":"SHA256E-s18792--1a765509384ea96b7b12136353d9c5b94f23d764ad0431e049197f7875eb352c.nwb","whereis":[{"here":false,"uuid":"00000000-0000-0000-0000-000000000001","urls":["https://api.dandiarchive.org/api/assets/ff453f4c-a435-4a5d-a48b-128abca5ec47/download/","https://dandiarchive.s3.amazonaws.com/blobs/2db/af0/2dbaf0fd-5003-4a0a-b4c0-bc8cdbdb3826?versionId=4BMLdtv04lfi7JDWFfUleHVzYazeFVL4"],"description":"web"},{"here":true,"uuid":"4ca7c743-c5d4-4e57-8ba7-ca3dc579591d","urls":[],"description":"dandi@drogon:/mnt/backup/dandi/dandisets/000027"}],"error-messages":[],"file":null}
whereis: 1 failed
```
</details>

and assume that if ~~0 copies~~ `"success":false` - not known.  May be there is a better way (@joeyh?)

> * How do I check whether a key is present in `dandi-dandisets-dropbox`?  Do I do `git-annex checkpresentkey $KEY dandi-dandisets-dropbox`?

yes AFAIK, or can just use output from aforementioned `whereis` which would list that key in there, just note that `dandi-dandisets-dropbox` is ATM among `untrusted` repos, and that might change, so better goes through all "levels"

> > given list of new assets to consider, sort by their creation date, choose the latest one which still has sha256 -- consider only those (all new assets with sha256 before/including that latest one)
> 
> Do you mean that you only want to consider the longest initial (by creation date) sequence of assets all with SHA256 digests?

yes.  so our timeline (and timestamps for commits) make more sense and history stays linear (which would not be so, if e.g. some later small asset gets SHA256 computed before some larger one uploaded before).

**Comment by jwodder** [comment]
@yarikoptic Problem: DANDI Archive's "Get asset metadata" endpoints only return asset metadata, without any of the fields (including "created") listed when paginating through assets.  As `dandi/dandiapi.py` needs to support initializing asset objects from just metadata, and as asset metadata does not include a "created" date, `dandiapi.py` asset objects do not provide or store the "created" date, and thus we can't sort assets by creation date.

**Comment by yarikoptic** [comment]
well, I guess we need to figure out how to tune up `dandi/dandiapi.py` to expose those fields as well. But meanwhile
- we can just use api endpoint directly for listing asset records, e.g. `curl -X GET "https://api.dandiarchive.org/api/dandisets/000027/versions/draft/assets/" -H  "accept: application/json"`
- and use `created` from there... but I also wonder if `modified` which we already somehow (how without `created`) have:
```shell
dandi@drogon:/mnt/backup/dandi/dandisets/000027$ grep -i modified -A1 .dandi/assets.json
"blobDateModified":
"2020-10-21T10:10:35.457789-04:00",
--
"dateModified":
"2021-06-29T18:59:29.491552-04:00",
--
"modified":
"2021-08-05T18:43:17.654105+00:00",
```
and just use that one?

**Comment by jwodder** [comment]
@yarikoptic 

> > * How do I check whether a key is present in `dandi-dandisets-dropbox`?  Do I do `git-annex checkpresentkey $KEY dandi-dandisets-dropbox`?
> 
> yes AFAIK, or can just use output from aforementioned `whereis` which would list that key in there, just note that `dandi-dandisets-dropbox` is ATM among `untrusted` repos, and that might change, so better goes through all "levels"

It appears that `checkpresentkey` works by connecting to the remote; trying the command out on the main dandi/dandisets clone on drogon fails with "remote currently unavailable or git-annex-remote-rclone failed to parse rclone output".

As for using `git-annex whereis`, for some reason the description for the dandi-dandisets-dropbox remote in whereis's output encloses the remote name in brackets; just how much variation in the description name should `backups2datalad.py` be prepared for?

**Comment by yarikoptic** [comment]
just strip `[` and `]`.
Enclosing in brackets IIRC just means that it is an enabled remote.  I would expect all of them to have it enabled, but better to not assume that.

**Comment by jwodder** [comment]
@yarikoptic Should the `--assetstore` functionality of the script be removed completely, or is it still possible that it'll continue to be used?  If the latter, what should happen if an asset exists in the assetstore but the Dandi Archive metadata lacks a SHA256 hash?  Should the hash be computed from the assetstore file, or should the asset not be copied?

**Comment by yarikoptic** [comment]
greedy me wants to say to keep that functionality, but I think -- let's just forget about --assetstore.
