### ISSUE TITLE
"Debounce" additions to git-annex

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#89]
I only now realized that by using 
```
                        with custom_commit_date(dandiset.version.modified):
                            ds.download_url(urls=bucket_url, path=a.path)
```
 we are producing a separate commit per each added file!  Although it is possibly most reflective of the evolution of the dataset, and makes it easier to guarantee that there is a state of the dandiset which is possibly released, it leads to "heavy" git history virtually for no UX benefit.  An alternative would be to "debounce" such additions but it might require a bit elaborate logic to trigger commits
- if there is a release for a given state (might be judged cheaply by `created` of known releases I guess)
- if added, but not committed asset is getting a new "version" (actually probably cannot happen)
- (not sure if needed) trigger at some temporal interval (e.g. after adding assets for over a day... commit message probably would notice that it is a "partial" state commit)

@jwodder ideas?

**Comment by jwodder** [comment]
@yarikoptic What exactly do you mean by "debounce"?  Can't we prevent the creation of separate commits by passing `save=False` to `download_url()`?

**Comment by yarikoptic** [comment]
;-) I called it "stagger" or "group" before, but then @waxlamp educated me about the "more proper" term.  The point is to not execute some action (e.g. "commit") right away whenever an event (e.g. new file added) happened.  And yes -- passing `save=False` would allow to avoid commit on each file addition.  But the actual interesting design aspect is to come up with optimal logic on when to trigger the action ("commit").  In the simplest case it could be "after all assets added", but then as I have mentioned in the original description it could become quite suboptimal if release has happened inbetween. Also that "timed commit" might be handy to assist in cases of crashes since it should allow to restart the process AFAIK (actually we might need extra work on how/when we "dump" the `.dandi/assets.jsonld` -- now it might be just after all assets downloaded, so may be in the case of #91 I actually ended up with inconsistent state, where that file is not actually representing the state in the file tree...)

**Comment by jwodder** [comment]
@yarikoptic 

> if there is a release for a given state (might be judged cheaply by `created` of known releases I guess)

Note that using just `version.created` to check for a release state won't catch assets deleted between the last run and the creation of the version, as the only way to identify deleted assets is by processing all current assets.  If we wanted to make more work for the dandi-api team, one way to handle all of this would be to add an endpoint to the API that returned a log of asset creation/modification/deletion and version creation events for a given Dandiset.

**Comment by yarikoptic** [comment]
well, the "audit" of actions is planned/being talked about, e.g. https://github.com/dandi/dandi-api/issues/525  but it would take awhile for us to get there.

Since we can "release" a published release from a modified state of a commit in the main (`draft`) branch, I think it would be ok if next commit in `draft` does not have some assets removed and for the release we do need to remove them in the commit which would later tag.

But also I don't think we should run into such situations if we add "release" `created` time point as the state for which we establish the tree in the `draft` branch before we go to consider the assets which are `created` after that point (in subsequent commit(s)) which would bring it to current `draft` state or yet another interim "released" state.

**Comment by yarikoptic** [comment]
I think we really need such "debouncing".  With a single file addition for 000108 we are now at  14k commits in that poor monster repo and that is not yet an entire dataset fetched:

```shell
dandi@drogon:/mnt/backup/dandi/dandisets/000108$ git log --pretty=oneline | nl  | tail
...
 14510  652912264c23b77a7a9839a47aeee94b53c99e24 [DATALAD] Download URLs
 14511  9be2e0029bf02eae82c7d5200fbbfb4996d29697 [DATALAD] Download URLs
 14512  8c8e38e8cc52517ed9dff049eb382e6543bb06a2 [DATALAD] Download URLs
 14513  8359d5c98cd0e7b1a4850a27d11ae2f599118dcb [backups2datalad]
 14514  3cca8315af58e44d620d0352e012f266d25268d3 Instruct annex to add text files to Git
 14515  55bc044205762644e55e54e31294879d84684f65 [DATALAD] new dataset

dandi@drogon:/mnt/backup/dandi/dandisets/000108$ du -scm .git/objects/
70      .git/objects/
70      total

dandi@drogon:/mnt/backup/dandi/dandisets/000108$ git annex info | grep 'size of annexed'
size of annexed files in working tree: 73.39 terabytes
```
FWIW that dandiset does not have any published version ATM, so in principle the rest of the files (~20TB if my algebra is correct) could be added in a single commit.
