### ISSUE TITLE
Make "backup" operation "out of band"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#93]
Related to #84 (to be addressed by # ) and #89 . I think we should
- mint annex keys and add files/urls without actual download of the content (could be extremely large) - will make "dataladification" fast and feasible to eventually happen straight on dandi-api instance
- have an out of bound process to actually (should do in a batch)
  - `git annex get` (or `datalad get`) the file (actually probably keys based on what is not `here` and not yet in `dandi-dandisets-dropbox`), that would also verify that checksum
    - it would be also more efficient than what we do now I believe -- download "manually" and then `annex add` - that causes extra IO to read the file for checksumming, whenever `annex get` now should do checksumming on the fly 
  - `git annex move --to dandi-dandisets-dropbox` 

The tricky part is to make both steps not to interfere.  I think it should be doable if in all cases we would just use batched processes. AFAIK git-annex works out quite well.

**Comment by yarikoptic** [comment]
FTR, ATM I am doing 
```
dandi@drogon:/mnt/backup/dandi/dandisets/000115$ git annex move -J6 --all --to dandi-dandisets-dropbox   --not --in dandi-dandisets-dropbox  --and --in here
dandi@drogon:/mnt/backup/dandi/dandisets/000115$ git annex find   --not --in dandi-dandisets-dropbox  --and --in here
dandi@drogon:/mnt/backup/dandi/dandisets/000115$ git annex drop -J6 --all  --in dandi-dandisets-dropbox  --and --in here
drop SHA256E-s158244563885--2b495178d4cb6cb66c82c39c5f508d0ea1d95925e2571dea6985327f481720fd.nwb (checking https://api.dandiarchive.org/api/assets/c665ae42-4583-4a2b-be3b-a0d28d810caf/download/...)
...
```
to 
- move (not just copy) what we have locally but not in dropbox
- verify that all are transferred
- `drop` locally

in principle, `move` should be sufficient (would kill two birds at once -- `copy` + `drop` AFAIK) and concise.

**Comment by jwodder** [comment]
@yarikoptic 

* If we add files by key without downloading them, how do we determine whether a file is a text file and thus should be excluded from git-annex?
* At what point should the out-of-band process be started, and by what point should it end?  Do you want it to continue running even after the main backup script finishes?  Do you want it to be started/managed by the backup script or manually run separately?

**Comment by yarikoptic** [comment]
good questions!  
- `git` vs `git-annex`: I guess we could start by deciding based on the file extension (.txt, .md, .yaml, .json and anything else we have in git not annex across dandisets ATM).  Theoretically (not sure if "ideally" since seems complex) - we could check if `python3-magic` somehow goes through python layer to open file, then we could use fsspec overloading `.open` and thus providing sparse access to the file.  If it just uses libmagic, I guess the only way is to use datalad-fuse or fsspec's fuse to provide access to that remote url to figure out if it would be considered to be text or not
- so it is either make it a tool to run on cron, or a "daemon" which would constantly monitor and react to changes.  I think the easiest would be to just start with a tool to trigger on cron.

**Comment by jwodder** [comment]
@yarikoptic What should the cronnable script's syntax be?  Would it just take a path to the backup superdandiset, possibly with a list of dandisets to get or exclude from getting?

Also, is there really a need to batch this?  Once the files are registered with git-annex, it seems you could download them with something like `git-annex get --not --in dandi-dandisets-dropbox  --and --not --in here`.

**Comment by yarikoptic** [comment]
> @yarikoptic What should the cronnable script's syntax be? Would it just take a path to the backup superdandiset, possibly with a list of dandisets to get or exclude from getting?

I think so.  I think also it should be just one more command in addition to the one(s) we already have in the `backups2datalad` .



> Also, is there really a need to batch this? Once the files are registered with git-annex, it seems you could download them with something like `git-annex get --not --in dandi-dandisets-dropbox --and --not --in here`.

correct -- that new command would be quite trivial -- just `get` and `move` .  Attention should be paid to failed `get`s though -- if we fail to download for some reason or checksum doesn't match the one we have in git-annex.

**Comment by jwodder** [comment]
@yarikoptic 

> Attention should be paid to failed `gets` though -- if we fail to download for some reason or checksum doesn't match the one we have in git-annex.

I believe `get` will exit with failure if any download fails.  Is that sufficient, or should the script monitor the command's output for details?

**Comment by yarikoptic** [comment]
don't know yet -- for now just failing when `get` fails (may be ran with `-c annex.retry=3` to account for possibly unstable connections etc) - output return records and or stderr  should suffice so we could troubleshoot and adjust accordingly if needed
