### ISSUE TITLE
ruamel.yaml conda dependency "is not enough"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#95]
I cannot try any of current PRs (such as #94) because instantiation of a new conda + pip environment results in inability to `import ruamel.yaml` within dandi-cli , which I also reported to https://github.com/conda-forge/ruamel.yaml-feedstock/issues/153 .
Odd enough the import works in "conda build" environment as was tried in https://github.com/conda-forge/dandi-feedstock/pull/56 and even tried after `conda install ruamel_yaml` (not even sure where it comes from).

We need a workaround or a fix for the ruamel.yaml conda pkg.

**Comment by jwodder** [comment]
@yarikoptic Have you tried just creating a non-conda virtualenv and installing the requirements with pip?

**Comment by jwodder** [comment]
@yarikoptic In your environment, if you do `conda install -c conda-forge ruamel_yaml`, can you then `import ruamel_yaml` (EDIT: or `import ruamel_yaml_conda`?)  If so, I can modify the script to try both imports.

(Incidentally, `ruamel_yaml` seems to come from [here](https://github.com/conda-forge/ruamel_yaml-feedstock); it's `ruamel.yaml` with some patches.)

**Comment by jwodder** [comment]
@yarikoptic The commit message for [this commit](https://github.com/conda-forge/ruamel_yaml-feedstock/commit/8a5610bd2f31aa039527c0e792bdc33a44e74a74) might be relevant to your problem.

**Comment by yarikoptic** [comment]
uff... that is quite an ugly backstory:  It makes little sense to demand upstream code to cater the distribution (conda). And I am still confused on how it worked before since I believe it used to work (but I could be wrong), and also -- why `ruamel.yaml` is not enough, i.e. what is wrong with that feedstock? what is missing and/or how the heck it works in the conda build env.

**Comment by jwodder** [comment]
@yarikoptic Seeing as installing ruamel.yaml works fine for me in a Docker container, perhaps your Conda is out of date somehow?

**Comment by yarikoptic** [comment]
do you mean that after running 
```
conda create -c conda-forge -n dandi-ruamel-troubleshoot -y ruamel.yaml
conda activate dandi-ruamel-troubleshoot
```
you are getting an importable `ruamel.yaml`?

edit: I am meanwhile updating conda on dandi@drogon (`4.9.2-py38h06a4308_0 --> 4.10.3-py38h06a4308_0`)

**Comment by jwodder** [comment]
@yarikoptic Yes, that works for me both in a Docker container and on drogon.

**Comment by yarikoptic** [comment]
damn it... I updated `conda` in the `base` env (had to leave `dandisets`) and then ran that `create` right there (in `base` not `dandisets` if that anyhow matters) and then import worked... uff...  I guess I will stop troubleshooting further - will finally try to test PRs ;)
