### ISSUE TITLE
Add coverage tracking + submission to codecov

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#98]
Just now realized while reviewing #97 that we are not submitting coverage to codecov.  Not sure if `async` nature of implementation would be somehow in the way, but I guess we would at least get some code annotated with coverage.

Could be done as part of the #97 or a separate PR

**Comment by jwodder** [comment]
@yarikoptic Coverage added to #97.

**Comment by yarikoptic** [comment]
so let's consider addressed
